/*
  Babu's directory of official pages.

  TOPICS  — the cards on the home page. `kw` words point a question at the topic.
  SERVICES — one entry per task. `kw` words point a question at that task.
             The first service in each topic is its default answer.
             links: u = official URL, n = site name (nh = Hindi name, optional).
             help  = official helpline, state = true if run by state governments.

  A keyword starting with "~" is weak: it scores less and only counts when the
  question also matches the service's topic. Use it for everyday words like
  "new", "name" or "apply" that mean different things in different topics.

  Keywords are matched case-insensitively. Short Latin words (3 letters or less)
  must match a whole word; longer ones match the start of a word ("certificate"
  also matches "certificates"). Hindi keywords match anywhere in the text.

  Links last reviewed: October 2026. Run tools/check_links.py from India to recheck.
*/
window.BABU_DATA = {
  reviewed: { en: "October 2026", hi: "अक्टूबर 2026" },

  TOPICS: [
    { id: "aadhaar", icon: "id", kw: ["aadhaar", "aadhar", "adhar", "uidai", "आधार"],
      en: { t: "Aadhaar", d: "Update address or details, download e-Aadhaar, find a centre.", q: "I moved to a new city. How do I update my Aadhaar address?" },
      hi: { t: "आधार", d: "पता या जानकारी बदलें, ई-आधार डाउनलोड करें, केंद्र खोजें।", q: "मैं नए शहर में आ गया हूँ। आधार में पता कैसे बदलूँ?" } },
    { id: "pan", icon: "card", kw: ["pan", "pan card", "e-pan", "epan", "पैन"],
      en: { t: "PAN card", d: "Instant e-PAN, Aadhaar linking, lost cards and corrections.", q: "My PAN card is lost. How do I get a new one?" },
      hi: { t: "पैन कार्ड", d: "इंस्टेंट ई-पैन, आधार लिंकिंग, खोया कार्ड और सुधार।", q: "मेरा पैन कार्ड खो गया है। नया कैसे मिलेगा?" } },
    { id: "passport", icon: "passport", kw: ["passport", "पासपोर्ट"],
      en: { t: "Passport", d: "New passports, renewals, children’s passports and tracking.", q: "How do I get a passport for my child?" },
      hi: { t: "पासपोर्ट", d: "नया पासपोर्ट, नवीनीकरण, बच्चों का पासपोर्ट और ट्रैकिंग।", q: "अपने बच्चे का पासपोर्ट कैसे बनवाऊँ?" } },
    { id: "voter", icon: "ballot", kw: ["voter", "vote", "voting", "epic", "election", "electoral", "वोटर", "वोट", "मतदाता", "चुनाव"],
      en: { t: "Voter ID", d: "Register to vote, find your name in the list, make corrections.", q: "How do I register to vote for the first time?" },
      hi: { t: "वोटर आईडी", d: "मतदाता पंजीकरण, सूची में नाम खोजना, जानकारी में सुधार।", q: "पहली बार वोटर के रूप में रजिस्टर कैसे करूँ?" } },
    { id: "dl", icon: "wheel", kw: ["driving", "licence", "license", "dl", "ड्राइविंग", "लाइसेंस"],
      en: { t: "Driving licence", d: "Learner’s licence, new licence, renewal and status.", q: "How do I renew my driving licence?" },
      hi: { t: "ड्राइविंग लाइसेंस", d: "लर्नर लाइसेंस, नया लाइसेंस, नवीनीकरण और स्टेटस।", q: "ड्राइविंग लाइसेंस का नवीनीकरण कैसे करूँ?" } },
    { id: "vehicle", icon: "car", kw: ["vehicle", "car", "bike", "scooter", "rc", "registration certificate", "गाड़ी", "वाहन", "बाइक", "कार", "स्कूटर"],
      en: { t: "Vehicles & challans", d: "RC transfer, vehicle registration and paying traffic challans.", q: "How do I pay my traffic challan?" },
      hi: { t: "वाहन और चालान", d: "RC ट्रांसफ़र, वाहन पंजीकरण और ट्रैफ़िक चालान भरना।", q: "ट्रैफ़िक चालान कैसे भरूँ?" } },
    { id: "ration", icon: "bag", kw: ["ration", "nfsa", "राशन"],
      en: { t: "Ration card", d: "New cards, adding family members, using your card in another state.", q: "How do I add my wife’s name to our ration card?" },
      hi: { t: "राशन कार्ड", d: "नया कार्ड, परिवार के सदस्य जोड़ना, दूसरे राज्य में कार्ड इस्तेमाल करना।", q: "राशन कार्ड में पत्नी का नाम कैसे जुड़वाऊँ?" } },
    { id: "tax", icon: "rupee", kw: ["income tax", "tax", "taxes", "itr", "आयकर", "टैक्स", "इनकम टैक्स"],
      en: { t: "Income tax", d: "Filing your ITR, refunds, paying tax and the tax calculator.", q: "I’m salaried. How do I file my income tax return?" },
      hi: { t: "आयकर", d: "आईटीआर भरना, रिफ़ंड, टैक्स भुगतान और टैक्स कैलकुलेटर।", q: "मैं नौकरी करता हूँ। आयकर रिटर्न कैसे भरूँ?" } },
    { id: "business", icon: "store", kw: ["business", "company", "shop", "startup", "msme", "firm", "व्यवसाय", "बिज़नेस", "बिजनेस", "कंपनी", "दुकान", "धंधा", "कारोबार"],
      en: { t: "Business & GST", d: "Udyam (MSME), GST, companies, food licences and selling to government.", q: "How do I register my small business?" },
      hi: { t: "व्यवसाय और जीएसटी", d: "उद्यम (MSME), जीएसटी, कंपनी, फ़ूड लाइसेंस और सरकार को बेचना।", q: "अपना छोटा व्यवसाय कैसे रजिस्टर करूँ?" } },
    { id: "birth", icon: "doc", kw: ["birth", "death", "जन्म", "मृत्यु"],
      en: { t: "Birth & death certificates", d: "Registering a birth or death and getting the certificate.", q: "How do I get my baby’s birth certificate?" },
      hi: { t: "जन्म और मृत्यु प्रमाण पत्र", d: "जन्म या मृत्यु का पंजीकरण और प्रमाण पत्र पाना।", q: "अपने बच्चे का जन्म प्रमाण पत्र कैसे बनवाऊँ?" } },
    { id: "health", icon: "health", kw: ["health", "hospital", "treatment", "medical", "ayushman", "स्वास्थ्य", "अस्पताल", "इलाज", "आयुष्मान"],
      en: { t: "Health cover", d: "Ayushman Bharat, cover for everyone 70+, ABHA ID and hospitals.", q: "Am I eligible for Ayushman Bharat?" },
      hi: { t: "स्वास्थ्य कवर", d: "आयुष्मान भारत, 70+ उम्र वालों का कवर, ABHA आईडी और अस्पताल।", q: "क्या मैं आयुष्मान भारत के लिए पात्र हूँ?" } },
    { id: "pf", icon: "coins", kw: ["pf", "epf", "epfo", "provident fund", "uan", "pension", "पीएफ", "भविष्य निधि", "पेंशन"],
      en: { t: "PF & pension", d: "PF balance, withdrawals, transfers and pensioners’ life certificates.", q: "How do I withdraw my PF after leaving a job?" },
      hi: { t: "पीएफ और पेंशन", d: "पीएफ बैलेंस, निकासी, ट्रांसफ़र और पेंशनर्स का जीवन प्रमाण पत्र।", q: "नौकरी छोड़ने के बाद पीएफ कैसे निकालूँ?" } },
    { id: "schemes", icon: "search", kw: ["scheme", "schemes", "yojana", "subsidy", "benefit", "योजना", "योजनाएँ", "सब्सिडी", "लाभ"],
      en: { t: "Schemes & benefits", d: "Find schemes, PM-Kisan, scholarships, housing, LPG and e-Shram.", q: "Which government schemes can a farmer in Bihar apply for?" },
      hi: { t: "योजनाएँ और लाभ", d: "योजनाएँ खोजें, पीएम-किसान, छात्रवृत्ति, आवास, एलपीजी और ई-श्रम।", q: "बिहार के किसान किन सरकारी योजनाओं के लिए आवेदन कर सकते हैं?" } },
    { id: "complaints", icon: "shield", kw: ["complaint", "complain", "fraud", "scam", "grievance", "report", "शिकायत", "धोखा", "धोखाधड़ी", "ठगी"],
      en: { t: "Complaints & fraud", d: "Cyber fraud, consumer complaints, lost phones and RTI.", q: "I lost money in a UPI fraud. What should I do?" },
      hi: { t: "शिकायत और धोखाधड़ी", d: "साइबर ठगी, उपभोक्ता शिकायत, खोया फ़ोन और आरटीआई।", q: "UPI फ्रॉड में पैसे कट गए। क्या करूँ?" } },
    { id: "documents", icon: "folder", kw: ["document", "documents", "digilocker", "दस्तावेज़", "डिजिलॉकर"],
      en: { t: "Documents & certificates", d: "DigiLocker, UMANG, and state certificates like caste, income and land records.", q: "How do I get an income certificate?" },
      hi: { t: "दस्तावेज़ और प्रमाण पत्र", d: "डिजिलॉकर, उमंग, और जाति, आय व ज़मीन के रिकॉर्ड जैसे राज्य प्रमाण पत्र।", q: "आय प्रमाण पत्र कैसे बनवाऊँ?" } },
    { id: "abroad", icon: "globe", kw: ["abroad", "foreign", "overseas", "nri", "oci", "visa", "embassy", "विदेश", "वीज़ा", "वीजा", "दूतावास", "एनआरआई"],
      en: { t: "Abroad & visas", d: "OCI cards, e-Visas and help from Indian embassies.", q: "How do I apply for an OCI card?" },
      hi: { t: "विदेश और वीज़ा", d: "OCI कार्ड, ई-वीज़ा और भारतीय दूतावासों से मदद।", q: "OCI कार्ड के लिए आवेदन कैसे करें?" } },
  ],

  SERVICES: [
    /* ---------- Aadhaar ---------- */
    { id: "aadhaar-update", topic: "aadhaar", help: "1947",
      links: [{ u: "https://myaadhaar.uidai.gov.in/", n: "myAadhaar" }],
      kw: ["address", "date of birth", "dob", "pata", "पता", "जन्मतिथि", "~update", "~change", "~correct", "~name", "~badal", "~बदल", "~सुधार", "~अपडेट", "~नाम"],
      en: { t: "Update the address or details on your Aadhaar", s: "Log in to myAadhaar with your Aadhaar number and an OTP, choose the update you need and upload a supporting document. Your address can be updated online; for a new mobile number, photo or fingerprints you need to visit an Aadhaar centre." },
      hi: { t: "आधार में पता या जानकारी बदलें", s: "आधार नंबर और OTP से myAadhaar में लॉगिन करें, ज़रूरी अपडेट चुनें और सहायक दस्तावेज़ अपलोड करें। पता ऑनलाइन बदला जा सकता है; मोबाइल नंबर, फ़ोटो या फ़िंगरप्रिंट बदलने के लिए आधार केंद्र जाना होगा।" } },
    { id: "aadhaar-download", topic: "aadhaar", help: "1947",
      links: [{ u: "https://myaadhaar.uidai.gov.in/", n: "myAadhaar" }],
      kw: ["download", "e-aadhaar", "eaadhaar", "pdf", "lost", "kho", "डाउनलोड", "ई-आधार", "खो", "~copy", "~कॉपी"],
      en: { t: "Download e-Aadhaar", s: "On myAadhaar, choose Download Aadhaar and enter your Aadhaar or enrolment number and the OTP. You get a password-protected PDF." },
      hi: { t: "ई-आधार डाउनलोड करें", s: "myAadhaar पर Download Aadhaar चुनें, आधार या एनरोलमेंट नंबर और OTP डालें। आपको पासवर्ड-सुरक्षित PDF मिलेगी।" } },
    { id: "aadhaar-status", topic: "aadhaar", help: "1947",
      links: [{ u: "https://myaadhaar.uidai.gov.in/", n: "myAadhaar" }],
      kw: ["urn", "enrolment id", "enrollment id", "eid", "~status", "~track", "~स्टेटस", "~स्थिति"],
      en: { t: "Check your Aadhaar enrolment or update status", s: "On myAadhaar, choose Check Enrolment & Update Status and enter your enrolment ID or Update Request Number (URN)." },
      hi: { t: "आधार एनरोलमेंट या अपडेट का स्टेटस देखें", s: "myAadhaar पर Check Enrolment & Update Status चुनें और अपना एनरोलमेंट आईडी या URN (अपडेट रिक्वेस्ट नंबर) डालें।" } },
    { id: "aadhaar-centre", topic: "aadhaar", help: "1947",
      links: [
        { u: "https://bhuvan.nrsc.gov.in/aadhaar/", n: "Aadhaar centre map (Bhuvan)", nh: "आधार केंद्र नक्शा (भुवन)" },
        { u: "https://appointments.uidai.gov.in/bookappointment.aspx", n: "UIDAI appointments", nh: "UIDAI अपॉइंटमेंट" },
      ],
      kw: ["centre", "center", "kendra", "appointment", "new aadhaar", "mobile number", "biometric", "fingerprint", "केंद्र", "सेंटर", "अपॉइंटमेंट", "नया आधार", "~enrol", "~enroll", "~mobile", "~photo", "~child", "~मोबाइल", "~बच्चे", "~फ़ोटो", "~फोटो"],
      en: { t: "Find an Aadhaar centre or book an appointment", s: "You need to visit a centre for a new Aadhaar and to change your mobile number, photo or fingerprints. Find one nearby on the map, or book a slot at a UIDAI-run centre." },
      hi: { t: "आधार केंद्र खोजें या अपॉइंटमेंट बुक करें", s: "नया आधार बनवाने और मोबाइल नंबर, फ़ोटो या फ़िंगरप्रिंट बदलने के लिए केंद्र जाना ज़रूरी है। नक्शे पर नज़दीकी केंद्र खोजें, या UIDAI केंद्र पर स्लॉट बुक करें।" } },

    /* ---------- PAN ---------- */
    { id: "pan-epan", topic: "pan", help: "1800 103 0025",
      links: [{ u: "https://eportal.incometax.gov.in/iec/foservices/#/pre-login/instant-e-pan", n: "Income Tax e-Filing", nh: "आयकर ई-फ़ाइलिंग" }],
      kw: ["new pan", "apply pan", "pan apply", "instant", "get pan", "first pan", "free pan", "नया पैन", "ई-पैन", "~new", "~apply", "~नया", "~बनवा"],
      en: { t: "Get a free instant e-PAN", s: "If your Aadhaar has a linked mobile number, you can get a PAN as a PDF in minutes, free of cost. Don’t apply if you already have a PAN — holding two is illegal." },
      hi: { t: "मुफ़्त इंस्टेंट ई-पैन पाएँ", s: "अगर आधार से मोबाइल नंबर जुड़ा है, तो कुछ ही मिनटों में मुफ़्त PDF पैन पाएँ। पहले से पैन है तो आवेदन न करें — दो पैन रखना ग़ैरक़ानूनी है।" } },
    { id: "pan-link", topic: "pan", help: "1800 103 0025",
      links: [
        { u: "https://eportal.incometax.gov.in/iec/foservices/#/pre-login/bl-link-aadhaar", n: "Link Aadhaar", nh: "आधार लिंक करें" },
        { u: "https://eportal.incometax.gov.in/iec/foservices/#/pre-login/link-aadhaar-status", n: "Link status", nh: "लिंक स्टेटस" },
      ],
      kw: ["link", "linking", "aadhaar link", "link status", "लिंक", "~जोड़"],
      en: { t: "Link your PAN with Aadhaar", s: "Link them on the Income Tax e-filing portal, or check whether they’re already linked." },
      hi: { t: "पैन को आधार से लिंक करें", s: "आयकर ई-फ़ाइलिंग पोर्टल पर पैन और आधार लिंक करें, या देखें कि वे पहले से जुड़े हैं या नहीं।" } },
    { id: "pan-reprint", topic: "pan",
      links: [
        { u: "https://onlineservices.proteantech.in/paam/ReprintEPan.html", n: "Protean — reprint", nh: "Protean — रीप्रिंट" },
        { u: "https://onlineservices.proteantech.in/paam/endUserRegisterContact.html", n: "Protean — corrections", nh: "Protean — सुधार" },
        { u: "https://www.pan.utiitsl.com/", n: "UTIITSL" },
      ],
      kw: ["lost", "kho", "खो", "reprint", "duplicate", "damaged", "डुप्लीकेट", "~correction", "~correct", "~change", "~name", "~physical", "~सुधार", "~गलत", "~ग़लत", "~नाम"],
      en: { t: "Replace a lost PAN card or correct your details", s: "Apply through the agency that issued your PAN — Protean (formerly NSDL) or UTIITSL. Both are authorised by the Income Tax Department. If you don’t know which, try your PAN on both." },
      hi: { t: "खोया पैन कार्ड दोबारा पाएँ या जानकारी सुधारें", s: "उसी एजेंसी से आवेदन करें जिसने आपका पैन जारी किया था — Protean (पहले NSDL) या UTIITSL। दोनों आयकर विभाग से अधिकृत हैं। पता न हो तो दोनों पर अपना पैन डालकर देखें।" } },
    { id: "pan-verify", topic: "pan",
      links: [{ u: "https://eportal.incometax.gov.in/iec/foservices/#/pre-login/verifyYourPAN", n: "Verify PAN", nh: "पैन सत्यापन" }],
      kw: ["verify pan", "check pan", "valid", "सत्यापन", "वैध", "~verify", "~active"],
      en: { t: "Check that a PAN is valid", s: "Confirm that a PAN is active and matches the holder’s name and date of birth." },
      hi: { t: "जाँचें कि पैन वैध है या नहीं", s: "पुष्टि करें कि पैन सक्रिय है और नाम व जन्मतिथि से मेल खाता है।" } },

    /* ---------- Passport ---------- */
    { id: "passport-apply", topic: "passport", help: "1800 258 1800",
      links: [{ u: "https://www.passportindia.gov.in/", n: "Passport Seva", nh: "पासपोर्ट सेवा" }],
      kw: ["renew", "renewal", "reissue", "tatkal", "minor", "तत्काल", "रिन्यू", "~new", "~expired", "~child", "~baby", "~banwa", "~नया", "~नवीनीकरण", "~बच्चे", "~बनवा"],
      en: { t: "Apply for or renew a passport", s: "Register on Passport Seva, fill in the form, pay the fee and book a slot at a Passport Seva Kendra or Post Office Passport Seva Kendra. Children need their own passport." },
      hi: { t: "पासपोर्ट के लिए आवेदन या नवीनीकरण करें", s: "पासपोर्ट सेवा पर रजिस्टर करें, फ़ॉर्म भरें, शुल्क दें और पासपोर्ट सेवा केंद्र या पोस्ट ऑफ़िस पासपोर्ट सेवा केंद्र में स्लॉट बुक करें। बच्चों का अलग पासपोर्ट बनता है।" } },
    { id: "passport-track", topic: "passport", help: "1800 258 1800",
      links: [{ u: "https://www.passportindia.gov.in/", n: "Passport Seva", nh: "पासपोर्ट सेवा" }],
      kw: ["file number", "dispatch", "police verification", "पुलिस वेरिफ़िकेशन", "~track", "~status", "~स्टेटस", "~ट्रैक"],
      en: { t: "Track your passport application", s: "Use Track Application Status on Passport Seva with your file number and date of birth." },
      hi: { t: "पासपोर्ट आवेदन का स्टेटस देखें", s: "पासपोर्ट सेवा पर Track Application Status में फ़ाइल नंबर और जन्मतिथि डालें।" } },

    /* ---------- Voter ID ---------- */
    { id: "voter-register", topic: "voter", help: "1950",
      links: [{ u: "https://voters.eci.gov.in/", n: "Voters’ Service Portal", nh: "वोटर सर्विस पोर्टल" }],
      kw: ["register to vote", "voter registration", "new voter", "form 6", "फ़ॉर्म 6", "फॉर्म 6", "नया वोटर", "~first time", "~register", "~पंजीकरण", "~पहली बार", "~रजिस्टर"],
      en: { t: "Register as a new voter", s: "Fill in Form 6 online on the Voters’ Service Portal. A Booth Level Officer then verifies your details." },
      hi: { t: "नए मतदाता के रूप में पंजीकरण करें", s: "वोटर सर्विस पोर्टल पर फ़ॉर्म 6 ऑनलाइन भरें। इसके बाद बूथ लेवल अधिकारी आपकी जानकारी की जाँच करते हैं।" } },
    { id: "voter-search", topic: "voter", help: "1950",
      links: [{ u: "https://electoralsearch.eci.gov.in/", n: "Electoral search", nh: "मतदाता सूची खोज" }],
      kw: ["voter list", "electoral roll", "polling", "booth", "find my name", "name in voter", "name in the voter", "name in list", "मतदान केंद्र", "बूथ", "~search", "~सूची", "~लिस्ट", "~नाम"],
      en: { t: "Find your name in the voter list", s: "Search the electoral roll by EPIC number, personal details or mobile number, and see your polling station." },
      hi: { t: "मतदाता सूची में अपना नाम खोजें", s: "EPIC नंबर, निजी जानकारी या मोबाइल नंबर से मतदाता सूची में नाम खोजें और अपना मतदान केंद्र देखें।" } },
    { id: "voter-correct", topic: "voter", help: "1950",
      links: [{ u: "https://voters.eci.gov.in/", n: "Voters’ Service Portal", nh: "वोटर सर्विस पोर्टल" }],
      kw: ["form 8", "e-epic", "shift", "download", "डाउनलोड", "~correction", "~correct", "~move", "~address", "~download", "~digital", "~सुधार", "~पता", "~शिफ्ट"],
      en: { t: "Correct details, shift address or download e-EPIC", s: "Use Form 8 to correct your details or shift your address, and download your digital voter ID (e-EPIC)." },
      hi: { t: "जानकारी सुधारें, पता बदलें या ई-EPIC डाउनलोड करें", s: "जानकारी सुधारने या पता बदलने के लिए फ़ॉर्म 8 भरें, और अपना डिजिटल वोटर आईडी (ई-EPIC) डाउनलोड करें।" } },

    /* ---------- Driving licence ---------- */
    { id: "dl-apply", topic: "dl",
      links: [{ u: "https://sarathi.parivahan.gov.in/sarathiservice/stateSelection.do", n: "Sarathi", nh: "सारथी" }],
      kw: ["learner", "learning", "ll", "new licence", "new license", "renew", "renewal", "international", "idp", "लर्नर", "~test", "~slot", "~expired", "~नया", "~नवीनीकरण", "~रिन्यू", "~टेस्ट"],
      en: { t: "Apply for a learner’s or driving licence, or renew one", s: "Choose your state on Sarathi, then apply, pay the fee and book a test slot." },
      hi: { t: "लर्नर या ड्राइविंग लाइसेंस के लिए आवेदन या नवीनीकरण", s: "सारथी पर अपना राज्य चुनें, फिर आवेदन करें, शुल्क दें और टेस्ट स्लॉट बुक करें।" } },
    { id: "dl-status", topic: "dl",
      links: [{ u: "https://sarathi.parivahan.gov.in/sarathiservice/stateSelection.do", n: "Sarathi", nh: "सारथी" }],
      kw: ["application status", "dl details", "~status", "~track", "~स्टेटस"],
      en: { t: "Check your licence application status", s: "On Sarathi, choose your state and open Application Status, or look up your licence details." },
      hi: { t: "लाइसेंस आवेदन का स्टेटस देखें", s: "सारथी पर अपना राज्य चुनें और Application Status खोलें, या अपने लाइसेंस की जानकारी देखें।" } },

    /* ---------- Vehicles ---------- */
    { id: "vehicle-rc", topic: "vehicle",
      links: [{ u: "https://parivahan.gov.in/", n: "Parivahan", nh: "परिवहन" }],
      kw: ["rc", "rc transfer", "vehicle registration", "register vehicle", "hypothecation", "noc", "duplicate rc", "road tax", "आरसी", "~transfer", "~ownership", "~ट्रांसफ़र", "~ट्रांसफर", "~मालिक"],
      en: { t: "RC transfer, vehicle registration and other RTO services", s: "On Parivahan, open Online Services → Vehicle Related Services and choose your state and RTO." },
      hi: { t: "RC ट्रांसफ़र, वाहन पंजीकरण और दूसरी RTO सेवाएँ", s: "परिवहन पोर्टल पर Online Services → Vehicle Related Services खोलें और अपना राज्य व RTO चुनें।" } },
    { id: "vehicle-challan", topic: "vehicle",
      links: [{ u: "https://echallan.parivahan.gov.in/", n: "e-Challan", nh: "ई-चालान" }],
      kw: ["challan", "traffic", "चालान", "ट्रैफ़िक", "ट्रैफिक", "~fine", "~penalty", "~जुर्माना"],
      en: { t: "Check or pay a traffic challan", s: "Look up challans by vehicle number, licence number or challan number, and pay online." },
      hi: { t: "ट्रैफ़िक चालान देखें या भरें", s: "वाहन नंबर, लाइसेंस नंबर या चालान नंबर से चालान देखें और ऑनलाइन भुगतान करें।" } },

    /* ---------- Ration card ---------- */
    { id: "ration-card", topic: "ration", state: true,
      links: [{ u: "https://nfsa.gov.in/portal/ration_card_state_portals_aa", n: "State ration card portals", nh: "राज्यों के राशन कार्ड पोर्टल" }],
      kw: ["~add", "~member", "~wife", "~husband", "~child", "~delete", "~remove", "~change", "~name", "~new", "~apply", "~banwa", "~जोड़", "~जुड़", "~नाम", "~नया", "~सदस्य", "~पत्नी", "~पति", "~बच्चे", "~बनवा"],
      en: { t: "Get a ration card, add members or make changes", s: "Ration cards are issued by your state. Pick your state from the official list to reach its food department portal." },
      hi: { t: "राशन कार्ड बनवाएँ, सदस्य जोड़ें या बदलाव करें", s: "राशन कार्ड आपका राज्य बनाता है। आधिकारिक सूची से अपना राज्य चुनकर उसके खाद्य विभाग के पोर्टल पर जाएँ।" } },
    { id: "ration-onorc", topic: "ration",
      links: [{ u: "https://nfsa.gov.in/", n: "NFSA" }],
      kw: ["one nation", "onorc", "another state", "other state", "migrant", "portability", "दूसरे राज्य", "वन नेशन"],
      en: { t: "Use your ration card in another state", s: "Under One Nation One Ration Card, NFSA ration card holders can collect their ration from any fair price shop in the country." },
      hi: { t: "दूसरे राज्य में राशन कार्ड इस्तेमाल करें", s: "वन नेशन वन राशन कार्ड के तहत NFSA राशन कार्ड धारक देश की किसी भी सरकारी राशन दुकान से राशन ले सकते हैं।" } },

    /* ---------- Income tax ---------- */
    { id: "itr-file", topic: "tax", help: "1800 103 0025",
      links: [{ u: "https://eportal.incometax.gov.in/iec/foservices/#/login", n: "Income Tax e-Filing", nh: "आयकर ई-फ़ाइलिंग" }],
      kw: ["itr", "file itr", "file return", "income tax return", "tax return", "e-verify", "form 16", "रिटर्न", "फ़ॉर्म 16", "~filing", "~salaried"],
      en: { t: "File your income tax return (ITR)", s: "Log in to the e-filing portal with your PAN, choose File Income Tax Return, and e-verify when you’re done." },
      hi: { t: "आयकर रिटर्न (ITR) भरें", s: "पैन से ई-फ़ाइलिंग पोर्टल में लॉगिन करें, File Income Tax Return चुनें और अंत में ई-वेरिफ़ाई करें।" } },
    { id: "tax-refund", topic: "tax", help: "1800 103 0025",
      links: [{ u: "https://eportal.incometax.gov.in/iec/foservices/#/login", n: "Income Tax e-Filing", nh: "आयकर ई-फ़ाइलिंग" }],
      kw: ["refund", "रिफंड", "रिफ़ंड", "वापसी"],
      en: { t: "Check your income tax refund", s: "Log in, then open e-File → Income Tax Returns → View Filed Returns to see the status of your return and refund." },
      hi: { t: "आयकर रिफ़ंड का स्टेटस देखें", s: "लॉगिन करें, फिर e-File → Income Tax Returns → View Filed Returns में रिटर्न और रिफ़ंड का स्टेटस देखें।" } },
    { id: "tax-pay", topic: "tax", help: "1800 103 0025",
      links: [{ u: "https://eportal.incometax.gov.in/iec/foservices/#/e-pay-tax-prelogin/user-details", n: "e-Pay Tax" }],
      kw: ["pay tax", "pay income tax", "tax payment", "advance tax", "self assessment", "challan 280", "टैक्स भुगतान", "टैक्स जमा", "~pay", "~payment", "~भुगतान", "~जमा"],
      en: { t: "Pay income tax online", s: "Use e-Pay Tax to pay advance tax, self-assessment tax and other dues. You don’t need to log in." },
      hi: { t: "आयकर का ऑनलाइन भुगतान करें", s: "एडवांस टैक्स, सेल्फ़-असेसमेंट टैक्स और दूसरे बकाया भरने के लिए e-Pay Tax इस्तेमाल करें — लॉगिन ज़रूरी नहीं।" } },
    { id: "tax-calc", topic: "tax",
      links: [{ u: "https://www.incometax.gov.in/iec/foportal/income-tax-calculator", n: "Tax calculator", nh: "टैक्स कैलकुलेटर" }],
      kw: ["calculate", "calculator", "how much tax", "कितना टैक्स", "कैलकुलेटर", "~regime"],
      en: { t: "Estimate your income tax", s: "Use the Income Tax Department’s official tax calculator." },
      hi: { t: "अपने आयकर का अनुमान लगाएँ", s: "आयकर विभाग के आधिकारिक टैक्स कैलकुलेटर का इस्तेमाल करें।" } },

    /* ---------- Business ---------- */
    { id: "udyam", topic: "business",
      links: [{ u: "https://udyamregistration.gov.in/UdyamRegistration.aspx", n: "Udyam Registration", nh: "उद्यम पंजीकरण" }],
      kw: ["udyam", "msme", "small business", "register business", "register my business", "udyog", "उद्यम", "एमएसएमई", "छोटा व्यवसाय", "छोटा बिज़नेस"],
      en: { t: "Register your small business (Udyam / MSME)", s: "Udyam registration for micro, small and medium businesses is free and online, using your Aadhaar and PAN." },
      hi: { t: "अपना छोटा व्यवसाय रजिस्टर करें (उद्यम / MSME)", s: "सूक्ष्म, लघु और मध्यम व्यवसायों के लिए उद्यम पंजीकरण मुफ़्त और ऑनलाइन है — इसके लिए आधार और पैन चाहिए।" } },
    { id: "gst-reg", topic: "business",
      links: [{ u: "https://reg.gst.gov.in/registration/", n: "GST registration", nh: "जीएसटी पंजीकरण" }],
      kw: ["gst", "gst registration", "gst number", "जीएसटी"],
      en: { t: "Register for GST", s: "Apply for a new GST registration on the GST portal and track your application." },
      hi: { t: "जीएसटी पंजीकरण करें", s: "जीएसटी पोर्टल पर नए पंजीकरण के लिए आवेदन करें और उसका स्टेटस देखें।" } },
    { id: "gst-search", topic: "business",
      links: [{ u: "https://services.gst.gov.in/services/searchtp", n: "Search taxpayer", nh: "करदाता खोज" }],
      kw: ["verify gst", "search gst", "check gst", "gstin", "gst number check", "जीएसटी नंबर जाँच"],
      en: { t: "Verify a GSTIN", s: "Check any business’s GST number, legal name and registration status." },
      hi: { t: "किसी GSTIN की जाँच करें", s: "किसी भी व्यवसाय का जीएसटी नंबर, क़ानूनी नाम और पंजीकरण स्टेटस देखें।" } },
    { id: "company", topic: "business",
      links: [{ u: "https://www.mca.gov.in/", n: "Ministry of Corporate Affairs", nh: "कॉर्पोरेट कार्य मंत्रालय" }],
      kw: ["company", "private limited", "pvt ltd", "llp", "incorporate", "incorporation", "कंपनी", "प्राइवेट लिमिटेड"],
      en: { t: "Start a company or LLP", s: "Companies and LLPs are incorporated online on the Ministry of Corporate Affairs (MCA) portal." },
      hi: { t: "कंपनी या LLP शुरू करें", s: "कंपनी और LLP का पंजीकरण कॉर्पोरेट कार्य मंत्रालय (MCA) के पोर्टल पर ऑनलाइन होता है।" } },
    { id: "fssai", topic: "business",
      links: [{ u: "https://foscos.fssai.gov.in/", n: "FSSAI FoSCoS" }],
      kw: ["fssai", "food", "food licence", "food license", "restaurant", "cloud kitchen", "फ़ूड", "फूड", "ढाबा", "~tiffin", "~खाना", "~होटल"],
      en: { t: "Get a food licence (FSSAI)", s: "Food businesses register or get a licence on FoSCoS, the FSSAI portal." },
      hi: { t: "फ़ूड लाइसेंस (FSSAI) लें", s: "खाने से जुड़े व्यवसाय FSSAI के FoSCoS पोर्टल पर पंजीकरण या लाइसेंस लेते हैं।" } },
    { id: "startup", topic: "business",
      links: [{ u: "https://www.startupindia.gov.in/", n: "Startup India" }],
      kw: ["startup", "start-up", "dpiit", "recognition", "स्टार्टअप"],
      en: { t: "Get recognised as a startup", s: "Apply for DPIIT startup recognition on Startup India." },
      hi: { t: "स्टार्टअप के रूप में मान्यता पाएँ", s: "Startup India पर DPIIT स्टार्टअप मान्यता के लिए आवेदन करें।" } },
    { id: "gem", topic: "business",
      links: [{ u: "https://gem.gov.in/", n: "GeM" }],
      kw: ["gem", "sell to government", "government tender", "tender", "supplier", "vendor", "टेंडर", "सरकार को बेच"],
      en: { t: "Sell to the government (GeM)", s: "Register as a seller on the Government e-Marketplace." },
      hi: { t: "सरकार को सामान बेचें (GeM)", s: "गवर्नमेंट ई-मार्केटप्लेस (GeM) पर विक्रेता के रूप में रजिस्टर करें।" } },

    /* ---------- Birth & death ---------- */
    { id: "birth-death", topic: "birth", state: true,
      links: [
        { u: "https://dc.crsorgi.gov.in/", n: "Civil Registration System", nh: "नागरिक पंजीकरण प्रणाली" },
        { u: "https://crsorgi.gov.in/", n: "CRS (other states)", nh: "CRS (अन्य राज्य)" },
      ],
      kw: ["birth certificate", "death certificate", "register birth", "register death", "newborn", "janam", "जन्म प्रमाण", "मृत्यु प्रमाण", "~baby", "~born", "~praman patra"],
      en: { t: "Register a birth or death and get the certificate", s: "Births and deaths should be registered within 21 days. Many states use the national CRS portal; others have their own, and the CRS site tells you which." },
      hi: { t: "जन्म या मृत्यु का पंजीकरण कराएँ और प्रमाण पत्र पाएँ", s: "जन्म और मृत्यु का पंजीकरण 21 दिनों के अंदर होना चाहिए। कई राज्य राष्ट्रीय CRS पोर्टल इस्तेमाल करते हैं, बाकी के अपने पोर्टल हैं — CRS साइट पर इसकी जानकारी है।" } },

    /* ---------- Health ---------- */
    { id: "ayushman", topic: "health", help: "14555",
      links: [{ u: "https://beneficiary.nha.gov.in/", n: "Ayushman beneficiary portal", nh: "आयुष्मान लाभार्थी पोर्टल" }],
      kw: ["ayushman", "pmjay", "pm-jay", "ayushman card", "golden card", "5 lakh", "insurance", "health insurance", "आयुष्मान कार्ड", "गोल्डन कार्ड", "~eligible", "~eligibility", "~पात्र", "~पात्रता"],
      en: { t: "Check Ayushman Bharat eligibility and get your card", s: "Log in with your mobile number to see if your family is covered, complete e-KYC and download the Ayushman card." },
      hi: { t: "आयुष्मान भारत की पात्रता देखें और कार्ड पाएँ", s: "मोबाइल नंबर से लॉगिन करके देखें कि आपका परिवार कवर है या नहीं, ई-KYC पूरा करें और आयुष्मान कार्ड डाउनलोड करें।" } },
    { id: "vay-vandana", topic: "health", help: "14555",
      links: [{ u: "https://beneficiary.nha.gov.in/", n: "Ayushman beneficiary portal", nh: "आयुष्मान लाभार्थी पोर्टल" }],
      kw: ["vay vandana", "vaya vandana", "seventy", "70", "elderly", "old age", "senior citizen", "वय वंदना", "70 साल", "बुज़ुर्ग", "बुजुर्ग", "वरिष्ठ", "~senior", "~parents", "~father", "~mother", "~dad", "~mom", "~papa", "~mummy", "~grandfather", "~grandmother", "~पिता", "~माँ", "~पापा", "~मम्मी", "~दादा", "~दादी", "~नाना", "~नानी", "~माता-पिता"],
      en: { t: "Free health cover for everyone aged 70+", s: "Every citizen aged 70 or above can get the Ayushman Vay Vandana card, whatever their income. Enrol with Aadhaar e-KYC." },
      hi: { t: "70+ उम्र वालों के लिए मुफ़्त स्वास्थ्य कवर", s: "70 या उससे ज़्यादा उम्र का हर नागरिक, आय कितनी भी हो, आयुष्मान वय वंदना कार्ड बनवा सकता है। आधार ई-KYC से नामांकन करें।" } },
    { id: "abha", topic: "health",
      links: [{ u: "https://abha.abdm.gov.in/", n: "ABHA" }],
      kw: ["abha", "health id", "health account", "health card", "abdm", "हेल्थ आईडी", "आभा"],
      en: { t: "Create your ABHA health ID", s: "A free 14-digit ID that keeps your health records together. Create it with Aadhaar or your driving licence." },
      hi: { t: "अपनी ABHA हेल्थ आईडी बनाएँ", s: "14 अंकों की मुफ़्त आईडी जो आपके स्वास्थ्य रिकॉर्ड एक जगह रखती है। इसे आधार या ड्राइविंग लाइसेंस से बनाएँ।" } },
    { id: "pmjay-hospitals", topic: "health", help: "14555",
      links: [{ u: "https://hospitals.pmjay.gov.in/", n: "Hospital finder", nh: "अस्पताल खोज" }],
      kw: ["hospital list", "empanelled", "find hospital", "which hospital", "nearest hospital", "hospitals", "accept", "अस्पताल सूची", "कौन सा अस्पताल", "कौन से अस्पताल"],
      en: { t: "Find a hospital that accepts Ayushman Bharat", s: "Search empanelled hospitals by state, district and speciality." },
      hi: { t: "आयुष्मान भारत वाले अस्पताल खोजें", s: "राज्य, ज़िला और विशेषज्ञता के हिसाब से सूचीबद्ध अस्पताल खोजें।" } },

    /* ---------- PF & pension ---------- */
    { id: "pf-balance", topic: "pf",
      links: [{ u: "https://passbook.epfindia.gov.in/MemberPassBook/login", n: "EPF passbook", nh: "EPF पासबुक" }],
      kw: ["passbook", "pf balance", "epf balance", "पासबुक", "~balance", "~how much", "~बैलेंस"],
      en: { t: "Check your PF balance", s: "Log in with your UAN to view your EPF passbook." },
      hi: { t: "पीएफ बैलेंस देखें", s: "UAN से लॉगिन करके अपनी EPF पासबुक देखें।" } },
    { id: "pf-withdraw", topic: "pf",
      links: [{ u: "https://unifiedportal-mem.epfindia.gov.in/memberinterface/", n: "EPFO Member portal", nh: "EPFO मेंबर पोर्टल" }],
      kw: ["withdraw", "withdrawal", "form 19", "form 31", "pension claim", "nikal", "निकाल", "निकासी", "~claim", "~advance", "~left job", "~क्लेम"],
      en: { t: "Withdraw PF or claim pension", s: "Log in to the Member portal, go to Online Services → Claim and choose the withdrawal you need. Your UAN must be linked to your Aadhaar and bank account." },
      hi: { t: "पीएफ निकालें या पेंशन क्लेम करें", s: "मेंबर पोर्टल में लॉगिन करें, Online Services → Claim में जाएँ और ज़रूरी निकासी चुनें। आपका UAN आधार और बैंक खाते से जुड़ा होना चाहिए।" } },
    { id: "pf-transfer", topic: "pf",
      links: [{ u: "https://unifiedportal-mem.epfindia.gov.in/memberinterface/", n: "EPFO Member portal", nh: "EPFO मेंबर पोर्टल" }],
      kw: ["uan activate", "activate uan", "new employer", "~transfer", "~new job", "~merge", "~activate", "~kyc", "~ट्रांसफ़र", "~ट्रांसफर", "~एक्टिवेट", "~नई नौकरी"],
      en: { t: "Transfer PF to a new employer or activate your UAN", s: "On the Member portal, activate your UAN, update your KYC and transfer your old PF account." },
      hi: { t: "पीएफ नई कंपनी में ट्रांसफ़र करें या UAN एक्टिवेट करें", s: "मेंबर पोर्टल पर UAN एक्टिवेट करें, KYC अपडेट करें और पुराना पीएफ खाता ट्रांसफ़र करें।" } },
    { id: "jeevan-pramaan", topic: "pf",
      links: [{ u: "https://jeevanpramaan.gov.in/", n: "Jeevan Pramaan", nh: "जीवन प्रमाण" }],
      kw: ["life certificate", "jeevan pramaan", "pensioner", "जीवन प्रमाण", "पेंशनर", "~pension", "~पेंशन"],
      en: { t: "Submit a pensioner’s life certificate", s: "Pensioners can submit a digital life certificate (Jeevan Pramaan) with Aadhaar authentication, including face authentication on a phone." },
      hi: { t: "पेंशनर्स का जीवन प्रमाण पत्र जमा करें", s: "पेंशनर्स आधार सत्यापन से डिजिटल जीवन प्रमाण पत्र (जीवन प्रमाण) जमा कर सकते हैं, फ़ोन पर फ़ेस ऑथेंटिकेशन से भी।" } },

    /* ---------- Schemes ---------- */
    { id: "myscheme", topic: "schemes",
      links: [{ u: "https://www.myscheme.gov.in/find-scheme", n: "myScheme" }],
      kw: ["find scheme", "government schemes", "list of schemes", "all schemes", "widow", "disability", "divyang", "किन योजनाओं", "कौन सी योजना", "सरकारी योजना", "विधवा", "दिव्यांग", "~which", "~eligible", "~women", "~senior", "~महिला"],
      en: { t: "Find government schemes you’re eligible for", s: "Answer a few questions on myScheme to see central and state schemes that fit you." },
      hi: { t: "अपने लिए सरकारी योजनाएँ खोजें", s: "myScheme पर कुछ सवालों के जवाब दें और अपने लिए केंद्र व राज्य की योजनाएँ देखें।" } },
    { id: "pm-kisan", topic: "schemes", help: "155261",
      links: [{ u: "https://pmkisan.gov.in/", n: "PM-Kisan", nh: "पीएम-किसान" }],
      kw: ["kisan", "farmer", "pm kisan", "installment", "instalment", "kist", "6000", "किसान", "किस्त", "किश्त", "खेती"],
      en: { t: "PM-Kisan: register, complete e-KYC or check your status", s: "Farmers can register, complete e-KYC and check their instalments under Know Your Status." },
      hi: { t: "पीएम-किसान: पंजीकरण, ई-KYC या स्टेटस", s: "किसान पंजीकरण कर सकते हैं, ई-KYC पूरा कर सकते हैं और Know Your Status में किस्तें देख सकते हैं।" } },
    { id: "scholarships", topic: "schemes",
      links: [{ u: "https://scholarships.gov.in/", n: "National Scholarship Portal", nh: "राष्ट्रीय छात्रवृत्ति पोर्टल" }],
      kw: ["scholarship", "छात्रवृत्ति", "स्कॉलरशिप", "~student", "~study", "~college", "~छात्र", "~पढ़ाई"],
      en: { t: "Scholarships for students", s: "Apply for central and many state scholarships on the National Scholarship Portal." },
      hi: { t: "छात्रों के लिए छात्रवृत्ति", s: "राष्ट्रीय छात्रवृत्ति पोर्टल पर केंद्र और कई राज्यों की छात्रवृत्तियों के लिए आवेदन करें।" } },
    { id: "pmay", topic: "schemes",
      links: [
        { u: "https://pmay-urban.gov.in/", n: "PMAY-Urban", nh: "PMAY-शहरी" },
        { u: "https://www.rural.gov.in/", n: "Ministry of Rural Development (PMAY-Gramin)", nh: "ग्रामीण विकास मंत्रालय (PMAY-ग्रामीण)" },
      ],
      kw: ["house", "housing", "awas", "pmay", "ghar", "makan", "घर", "मकान", "आवास", "~home"],
      en: { t: "Help with a home: PM Awas Yojana", s: "In towns and cities, apply under PMAY-Urban. In villages, PMAY-Gramin beneficiaries are chosen through surveys and the Gram Sabha — ask your gram panchayat." },
      hi: { t: "घर के लिए मदद: प्रधानमंत्री आवास योजना", s: "शहरों में PMAY-शहरी के तहत आवेदन करें। गाँवों में PMAY-ग्रामीण के लाभार्थी सर्वे और ग्राम सभा से चुने जाते हैं — अपनी ग्राम पंचायत से पूछें।" } },
    { id: "ujjwala", topic: "schemes",
      links: [{ u: "https://pmuy.gov.in/", n: "PM Ujjwala Yojana", nh: "प्रधानमंत्री उज्ज्वला योजना" }],
      kw: ["lpg", "gas", "cylinder", "ujjwala", "cooking gas", "गैस", "सिलेंडर", "उज्ज्वला"],
      en: { t: "Free LPG connection (Ujjwala)", s: "Women from poor households can apply for a free LPG connection under PM Ujjwala Yojana." },
      hi: { t: "मुफ़्त एलपीजी कनेक्शन (उज्ज्वला)", s: "गरीब परिवारों की महिलाएँ प्रधानमंत्री उज्ज्वला योजना के तहत मुफ़्त एलपीजी कनेक्शन के लिए आवेदन कर सकती हैं।" } },
    { id: "eshram", topic: "schemes",
      links: [{ u: "https://eshram.gov.in/", n: "e-Shram", nh: "ई-श्रम" }],
      kw: ["eshram", "e-shram", "shram", "labour", "labor", "labourer", "unorganised", "unorganized", "daily wage", "मज़दूर", "मजदूर", "श्रमिक", "ई-श्रम", "श्रम", "~worker", "~gig", "~delivery", "~domestic"],
      en: { t: "e-Shram card for unorganised workers", s: "Workers without PF or ESIC — such as labourers, domestic workers and gig workers — can register for free." },
      hi: { t: "असंगठित श्रमिकों के लिए ई-श्रम कार्ड", s: "जिन श्रमिकों का पीएफ या ESIC नहीं है — जैसे मज़दूर, घरेलू कामगार और गिग वर्कर — मुफ़्त में रजिस्टर कर सकते हैं।" } },
    { id: "vishwakarma", topic: "schemes",
      links: [{ u: "https://pmvishwakarma.gov.in/", n: "PM Vishwakarma", nh: "पीएम विश्वकर्मा" }],
      kw: ["vishwakarma", "artisan", "carpenter", "tailor", "potter", "blacksmith", "barber", "craftsman", "कारीगर", "विश्वकर्मा", "दर्ज़ी", "दर्जी", "बढ़ई", "कुम्हार", "लोहार", "नाई"],
      en: { t: "PM Vishwakarma for artisans", s: "Traditional artisans and craftspeople — carpenters, tailors, potters and more — can get training, a toolkit grant and loans." },
      hi: { t: "कारीगरों के लिए पीएम विश्वकर्मा", s: "पारंपरिक कारीगर — बढ़ई, दर्ज़ी, कुम्हार आदि — प्रशिक्षण, टूलकिट अनुदान और लोन पा सकते हैं।" } },

    /* ---------- Complaints & fraud ---------- */
    { id: "cyber-fraud", topic: "complaints", help: "1930",
      links: [{ u: "https://cybercrime.gov.in/", n: "Cyber crime portal", nh: "साइबर क्राइम पोर्टल" }],
      kw: ["cyber", "online fraud", "upi fraud", "upi", "scam", "hacked", "otp fraud", "money lost", "lost money", "sextortion", "digital arrest", "फ्रॉड", "साइबर", "ठगी", "पैसे कट", "हैक", "डिजिटल अरेस्ट"],
      en: { t: "Report online fraud or cyber crime", s: "Lost money to a scam? Call 1930 straight away — acting fast gives the best chance of stopping the money — then file a complaint on the cyber crime portal." },
      hi: { t: "ऑनलाइन धोखाधड़ी या साइबर अपराध की शिकायत करें", s: "किसी ठगी में पैसे गए हैं? तुरंत 1930 पर कॉल करें — जल्दी करने से पैसे रुकने की संभावना सबसे ज़्यादा होती है — फिर साइबर क्राइम पोर्टल पर शिकायत दर्ज करें।" } },
    { id: "consumer", topic: "complaints", help: "1915",
      links: [{ u: "https://consumerhelpline.gov.in/", n: "National Consumer Helpline", nh: "राष्ट्रीय उपभोक्ता हेल्पलाइन" }],
      kw: ["consumer", "refund not received", "defective", "faulty", "cheated", "warranty", "उपभोक्ता", "सामान खराब", "~product", "~ecommerce", "~e-commerce", "~ख़राब"],
      en: { t: "Complain about a product or company", s: "Raise a consumer complaint with the National Consumer Helpline — online or by calling 1915." },
      hi: { t: "किसी सामान या कंपनी की शिकायत करें", s: "राष्ट्रीय उपभोक्ता हेल्पलाइन पर ऑनलाइन या 1915 पर कॉल करके शिकायत दर्ज करें।" } },
    { id: "cpgrams", topic: "complaints",
      links: [{ u: "https://pgportal.gov.in/", n: "CPGRAMS" }],
      kw: ["grievance", "cpgrams", "pgportal", "government office", "सरकारी दफ़्तर", "सरकारी दफ्तर", "~department", "~officer", "~delay", "~विभाग", "~देरी"],
      en: { t: "Complain about a government department", s: "File a grievance against a central or state government office on CPGRAMS and track it." },
      hi: { t: "किसी सरकारी विभाग की शिकायत करें", s: "CPGRAMS पर केंद्र या राज्य सरकार के किसी दफ़्तर के ख़िलाफ़ शिकायत दर्ज करें और उसे ट्रैक करें।" } },
    { id: "rti", topic: "complaints",
      links: [{ u: "https://rtionline.gov.in/", n: "RTI Online", nh: "आरटीआई ऑनलाइन" }],
      kw: ["rti", "right to information", "सूचना का अधिकार", "आरटीआई"],
      en: { t: "File an RTI application", s: "Ask any central government public authority for information online, for a ₹10 fee. Many states run their own RTI portals." },
      hi: { t: "आरटीआई आवेदन दाखिल करें", s: "केंद्र सरकार के किसी भी सार्वजनिक प्राधिकरण से ₹10 शुल्क देकर ऑनलाइन जानकारी माँगें। कई राज्यों के अपने आरटीआई पोर्टल हैं।" } },
    { id: "lost-phone", topic: "complaints",
      links: [{ u: "https://sancharsaathi.gov.in/", n: "Sanchar Saathi", nh: "संचार साथी" }],
      kw: ["lost phone", "lost my phone", "lost my mobile", "stolen phone", "stolen mobile", "phone stolen", "phone lost", "mobile chori", "stolen", "theft", "chori", "imei", "block phone", "ceir", "फ़ोन खो", "फोन खो", "मोबाइल खो", "मोबाइल चोरी", "फ़ोन चोरी", "फोन चोरी", "चोरी", "~phone", "~mobile"],
      en: { t: "Block a lost or stolen phone", s: "Report it to the police, then block the phone on Sanchar Saathi so it can’t be used on any network in India." },
      hi: { t: "खोया या चोरी हुआ फ़ोन ब्लॉक करें", s: "पुलिस में रिपोर्ट करें, फिर संचार साथी पर फ़ोन ब्लॉक करें ताकि भारत में किसी भी नेटवर्क पर उसका इस्तेमाल न हो सके।" } },
    { id: "sim-check", topic: "complaints",
      links: [{ u: "https://sancharsaathi.gov.in/", n: "Sanchar Saathi", nh: "संचार साथी" }],
      kw: ["sim", "sims", "mobile connections", "connections in my name", "in my name", "fraud call", "spam call", "fake call", "chakshu", "सिम", "फ़र्ज़ी कॉल", "फर्जी कॉल"],
      en: { t: "See which SIM cards are in your name, or report fraud calls", s: "Check the mobile connections issued against your ID, and report suspected fraud calls or messages." },
      hi: { t: "देखें आपके नाम पर कौन-से सिम हैं, या फ़र्ज़ी कॉल की शिकायत करें", s: "अपनी आईडी पर जारी मोबाइल कनेक्शन देखें, और संदिग्ध फ़्रॉड कॉल या मैसेज की शिकायत करें।" } },

    /* ---------- Documents & certificates ---------- */
    { id: "state-certificates", topic: "documents", state: true,
      links: [{ u: "https://www.india.gov.in/services", n: "National services directory", nh: "राष्ट्रीय सेवा निर्देशिका" }],
      kw: ["caste", "income certificate", "domicile", "residence certificate", "land record", "land", "khata", "khasra", "khatauni", "jamabandi", "bhulekh", "marriage", "jati", "aay praman", "जाति", "आय प्रमाण", "निवास", "ज़मीन", "जमीन", "भूलेख", "खसरा", "खतौनी", "शादी", "विवाह"],
      en: { t: "Caste, income or domicile certificates, land records, marriage registration", s: "These are run by your state government, usually through its e-district or land records portal. Start from the national services directory." },
      hi: { t: "जाति, आय या निवास प्रमाण पत्र, ज़मीन के रिकॉर्ड, विवाह पंजीकरण", s: "ये सेवाएँ आपकी राज्य सरकार देती है, आम तौर पर उसके ई-डिस्ट्रिक्ट या भूलेख पोर्टल से। राष्ट्रीय सेवा निर्देशिका से शुरुआत करें।" } },
    { id: "digilocker", topic: "documents",
      links: [{ u: "https://www.digilocker.gov.in/", n: "DigiLocker", nh: "डिजिलॉकर" }],
      kw: ["digilocker", "digital copy", "marksheet", "mark sheet", "marks card", "documents on phone", "डिजिलॉकर", "मार्कशीट"],
      en: { t: "Keep official documents on your phone (DigiLocker)", s: "Get digital copies of your driving licence, vehicle RC, marksheets and more, issued directly by the departments." },
      hi: { t: "सरकारी दस्तावेज़ फ़ोन में रखें (डिजिलॉकर)", s: "ड्राइविंग लाइसेंस, वाहन RC, मार्कशीट आदि की डिजिटल कॉपी सीधे विभागों से पाएँ।" } },
    { id: "umang", topic: "documents",
      links: [{ u: "https://web.umang.gov.in/", n: "UMANG", nh: "उमंग" }],
      kw: ["umang", "उमंग", "~app", "~one app", "~ऐप"],
      en: { t: "Many government services in one app (UMANG)", s: "Use UMANG on the web or as an app for services from central and state departments." },
      hi: { t: "एक ही ऐप में कई सरकारी सेवाएँ (उमंग)", s: "केंद्र और राज्य विभागों की सेवाओं के लिए उमंग को वेब पर या ऐप में इस्तेमाल करें।" } },

    /* ---------- Abroad & visas ---------- */
    { id: "oci", topic: "abroad",
      links: [{ u: "https://ociservices.gov.in/", n: "OCI Services", nh: "OCI सेवाएँ" }],
      kw: ["oci", "overseas citizen", "pio", "ओसीआई"],
      en: { t: "Apply for an OCI card", s: "Foreign citizens of Indian origin, and foreign spouses of Indian citizens or OCI holders, can apply online." },
      hi: { t: "OCI कार्ड के लिए आवेदन करें", s: "भारतीय मूल के विदेशी नागरिक, और भारतीय नागरिकों या OCI धारकों के विदेशी जीवनसाथी, ऑनलाइन आवेदन कर सकते हैं।" } },
    { id: "evisa", topic: "abroad",
      links: [{ u: "https://indianvisaonline.gov.in/evisa/", n: "Indian e-Visa", nh: "भारतीय ई-वीज़ा" }],
      kw: ["visa", "e-visa", "evisa", "tourist visa", "foreigner", "visit india", "वीज़ा", "वीजा"],
      en: { t: "Indian e-Visa for foreign visitors", s: "Foreign nationals can apply online for tourist, business, medical and other e-Visas." },
      hi: { t: "विदेशी यात्रियों के लिए भारतीय ई-वीज़ा", s: "विदेशी नागरिक पर्यटन, व्यापार, इलाज और अन्य ई-वीज़ा के लिए ऑनलाइन आवेदन कर सकते हैं।" } },
    { id: "madad", topic: "abroad",
      links: [{ u: "https://madad.gov.in/", n: "MADAD", nh: "मदद" }],
      kw: ["madad", "embassy", "consulate", "stuck abroad", "help abroad", "दूतावास", "विदेश में फँसे", "विदेश में फंसे", "~mission"],
      en: { t: "Help from an Indian embassy abroad (MADAD)", s: "Indians abroad can raise consular problems — emergencies, unpaid wages, bringing home mortal remains — with Indian missions." },
      hi: { t: "विदेश में भारतीय दूतावास से मदद (मदद पोर्टल)", s: "विदेश में रहने वाले भारतीय आपात स्थिति, बकाया वेतन या पार्थिव शरीर वापस लाने जैसे मामलों में भारतीय मिशनों से मदद माँग सकते हैं।" } },
  ],
};
