/*
  Babu's directory of state and union territory portals.

  links: c = category (services, land, ration, birth, grievance, rti, portal), u = official URL,
         n = portal name, nh = Hindi name. crs = true if the state registers births and deaths on the
         national Civil Registration System (dc.crsorgi.gov.in).
  codes:  short forms that only count in capitals ("UP", "MP"). A state found only by its code is used
          for that answer but not remembered. help: wa = true for a WhatsApp-only number.
  aliases, cities: other words that point a question at this state; matched as whole words, and a
          name in brackets counts on its own ("Margao (Madgaon)"). Leave out names that are also ordinary
          words or personal names (Gaya, Puri, Anand, Rohini…) or that exist in two states.

  Researched and independently re-verified October 2026. Many state sites only open from India —
  run tools/check_links.py from an Indian connection to recheck.
*/
window.BABU_STATES = [
  { id: "andaman-and-nicobar-islands", type: "ut", en: "Andaman and Nicobar Islands", hi: "अंडमान और निकोबार द्वीपसमूह", crs: true,
    codes: [], aliases: ["Andaman", "Andaman & Nicobar", "Andaman Nicobar", "Andaman and Nicobar", "अंडमान", "अंडमान एवं निकोबार", "अंडमान तथा निकोबार", "अंडमान निकोबार"],
    cities: [{"en": "Sri Vijaya Puram (Port Blair)", "hi": "श्री विजयपुरम (पोर्ट ब्लेयर)"}, {"en": "Mayabunder", "hi": "मायाबंदर"}, {"en": "Car Nicobar", "hi": "कार निकोबार"}, {"en": "Diglipur", "hi": "डिगलीपुर"}, {"en": "Rangat", "hi": "रंगत"}, {"en": "Campbell Bay", "hi": "कैंपबेल बे"}, {"en": "Hut Bay", "hi": "हट बे"}, {"en": "Swaraj Dweep (Havelock)", "hi": "स्वराज द्वीप"}],
    links: [
      { c: "services", u: "https://anieseva.andamannicobar.gov.in/", n: "ANI e-Seva", nh: "एएनआई ई-सेवा" },
      { c: "ration", u: "https://dcsca.andamannicobar.gov.in/", n: "Civil Supplies & Consumer Affairs Department, A&N", nh: "नागरिक आपूर्ति एवं उपभोक्ता मामले विभाग, अंडमान व निकोबार" },
      { c: "grievance", u: "https://db.and.nic.in/lghelpdesk/", n: "LG Helpdesk – Citizen Grievance Filing & Redressal", nh: "उपराज्यपाल हेल्पडेस्क – नागरिक शिकायत निवारण पोर्टल" },
      { c: "portal", u: "https://andamannicobar.gov.in/", n: "Andaman & Nicobar Administration", nh: "अंडमान तथा निकोबार प्रशासन" },
    ],
    help: [] },
  { id: "andhra-pradesh", type: "state", en: "Andhra Pradesh", hi: "आंध्र प्रदेश", crs: true,
    codes: ["AP"], aliases: ["Andhra", "आंध्र", "आन्ध्र प्रदेश"],
    cities: [{"en": "Visakhapatnam", "hi": "विशाखापत्तनम"}, {"en": "Vijayawada", "hi": "विजयवाड़ा"}, {"en": "Guntur", "hi": "गुंटूर"}, {"en": "Nellore", "hi": "नेल्लोर"}, {"en": "Kurnool", "hi": "कुरनूल"}, {"en": "Tirupati", "hi": "तिरुपति"}, {"en": "Kakinada", "hi": "काकीनाडा"}, {"en": "Rajamahendravaram", "hi": "राजमहेंद्रवरम"}, {"en": "Kadapa", "hi": "कडपा"}, {"en": "Anantapur", "hi": "अनंतपुर"}, {"en": "Vizag", "hi": "विज़ाग"}],
    links: [
      { c: "services", u: "https://apseva.ap.gov.in/", n: "AP Seva (Swarna Gramam Swarna Wardu)", nh: "एपी सेवा (स्वर्ण ग्रामम स्वर्ण वार्डु)" },
      { c: "land", u: "https://meebhoomi.ap.gov.in/", n: "Meebhoomi", nh: "मीभूमि" },
      { c: "ration", u: "https://civilsupplies.ap.gov.in/", n: "Consumer Affairs, Food & Civil Supplies Department, AP", nh: "उपभोक्ता मामले, खाद्य एवं नागरिक आपूर्ति विभाग, आंध्र प्रदेश" },
      { c: "grievance", u: "https://pgrs.ap.gov.in/", n: "PGRS (Public Grievance Redressal System)", nh: "पीजीआरएस (जन शिकायत निवारण प्रणाली)" },
      { c: "portal", u: "https://www.ap.gov.in/", n: "Government of Andhra Pradesh", nh: "आंध्र प्रदेश सरकार" },
    ],
    help: [] },
  { id: "arunachal-pradesh", type: "state", en: "Arunachal Pradesh", hi: "अरुणाचल प्रदेश", crs: true,
    codes: [], aliases: ["Arunachal", "Arunachal Pradesh", "North-East Frontier Agency", "अरुणाचल", "अरुणाचल प्रदेश"],
    cities: [{"en": "Itanagar", "hi": "ईटानगर"}, {"en": "Naharlagun", "hi": "नाहरलगुन"}, {"en": "Pasighat", "hi": "पासीघाट"}, {"en": "Tawang", "hi": "तवांग"}, {"en": "Bomdila", "hi": "बोमडिला"}, {"en": "Tezu", "hi": "तेज़ू"}, {"en": "", "hi": "आलो"}, {"en": "Roing", "hi": "रोइंग"}, {"en": "Namsai", "hi": "नामसाई"}],
    links: [
      { c: "services", u: "https://eservice.arunachal.gov.in/", n: "Arunachal eServices", nh: "अरुणाचल ई-सर्विसेज़" },
      { c: "land", u: "https://lisa.arunachal.gov.in/", n: "LISA – Land Information System of Arunachal Pradesh", nh: "लीसा – अरुणाचल प्रदेश भूमि सूचना प्रणाली" },
      { c: "ration", u: "https://arunfcs.gov.in/", n: "Department of Food & Civil Supplies, Arunachal Pradesh", nh: "खाद्य एवं नागरिक आपूर्ति विभाग, अरुणाचल प्रदेश" },
      { c: "grievance", u: "https://cmejansunwai.arunachal.gov.in/", n: "CM e-Jansunwai", nh: "सीएम ई-जनसुनवाई" },
      { c: "portal", u: "https://arunachalpradesh.gov.in/", n: "Arunachal Pradesh State Portal", nh: "अरुणाचल प्रदेश राज्य पोर्टल" },
    ],
    help: [{"num": "1076", "en": "CM Jansunwai grievance helpline", "hi": "सीएम जनसुनवाई शिकायत हेल्पलाइन"}] },
  { id: "assam", type: "state", en: "Assam", hi: "असम", crs: true,
    codes: [], aliases: ["Assam", "असम", "आसाम"],
    cities: [{"en": "Guwahati", "hi": "गुवाहाटी"}, {"en": "Dispur", "hi": "दिसपुर"}, {"en": "Dibrugarh", "hi": "डिब्रूगढ़"}, {"en": "Silchar", "hi": "सिलचर"}, {"en": "Jorhat", "hi": "जोरहाट"}, {"en": "Tezpur", "hi": "तेज़पुर"}, {"en": "Nagaon", "hi": "नगाँव"}, {"en": "Tinsukia", "hi": "तिनसुकिया"}, {"en": "Bongaigaon", "hi": "बोंगाईगाँव"}, {"en": "Diphu", "hi": "दिफू"}, {"en": "Gauhati", "hi": ""}],
    links: [
      { c: "services", u: "https://sewasetu.assam.gov.in/", n: "Sewa Setu", nh: "सेवा सेतु" },
      { c: "land", u: "https://ilrms.assam.gov.in/", n: "ILRMS – Integrated Land Records Management System", nh: "आईएलआरएमएस – एकीकृत भूमि अभिलेख प्रबंधन प्रणाली" },
      { c: "ration", u: "https://fcsca.assam.gov.in/", n: "Food, Public Distribution & Consumer Affairs Department, Assam", nh: "खाद्य, सार्वजनिक वितरण एवं उपभोक्ता मामले विभाग, असम" },
      { c: "grievance", u: "https://pgportal.gov.in/", n: "CPGRAMS (grievance system adopted by Govt of Assam)", nh: "सीपीग्राम्स (असम सरकार द्वारा अपनाई गई शिकायत प्रणाली)" },
      { c: "portal", u: "https://assam.gov.in/", n: "Assam State Portal", nh: "असम राज्य पोर्टल" },
    ],
    help: [{"num": "1800-345-3611", "en": "Food & PDS (ration) grievance toll-free number", "hi": "खाद्य एवं राशन (पीडीएस) शिकायत टोल-फ्री नंबर"}] },
  { id: "bihar", type: "state", en: "Bihar", hi: "बिहार", crs: true,
    codes: [], aliases: ["Behar", "Bihar State", "बिहार", "बिहार राज्य"],
    cities: [{"en": "Patna", "hi": "पटना"}, {"en": "Bhagalpur", "hi": "भागलपुर"}, {"en": "Muzaffarpur", "hi": "मुज़फ़्फ़रपुर"}, {"en": "Darbhanga", "hi": "दरभंगा"}, {"en": "Purnia", "hi": "पूर्णिया"}, {"en": "Begusarai", "hi": "बेगूसराय"}, {"en": "Arrah", "hi": ""}, {"en": "Chhapra", "hi": "छपरा"}, {"en": "Bihar Sharif", "hi": "बिहार शरीफ"}],
    links: [
      { c: "services", u: "https://serviceonline.bihar.gov.in/", n: "RTPS Bihar (ServiceOnline)", nh: "आरटीपीएस बिहार (सर्विसऑनलाइन)" },
      { c: "land", u: "https://biharbhumi.bihar.gov.in/Biharbhumi/", n: "Bihar Bhumi", nh: "बिहार भूमि" },
      { c: "ration", u: "https://epds.bihar.gov.in/", n: "EPDS Bihar (Ration Card Management System)", nh: "ईपीडीएस बिहार (राशन कार्ड प्रबंधन प्रणाली)" },
      { c: "grievance", u: "https://lokshikayat.bihar.gov.in/", n: "Bihar Lok Shikayat Nivaran (BPGRS)", nh: "बिहार लोक शिकायत निवारण" },
      { c: "rti", u: "https://jaankari.bihar.gov.in/", n: "Jaankari – Bihar RTI Portal", nh: "जानकारी – बिहार आरटीआई पोर्टल" },
      { c: "portal", u: "https://state.bihar.gov.in/", n: "Government of Bihar State Portal", nh: "बिहार सरकार राज्य पोर्टल" },
    ],
    help: [{"num": "1100", "en": "Sahyog Helpline – CM Secretariat grievance helpline (8 AM–8 PM, working days)", "hi": "सहयोग हेल्पलाइन – मुख्यमंत्री सचिवालय शिकायत हेल्पलाइन (सुबह 8 से रात 8 बजे, कार्य दिवस)"}, {"num": "18003456284", "en": "Bihar Lok Shikayat toll-free – file a public grievance or check its status (daily, 9:30 AM–6:30 PM)", "hi": "बिहार लोक शिकायत टोल फ्री – परिवाद दायर करने या स्थिति जानने हेतु (प्रतिदिन सुबह 9:30 से शाम 6:30)"}, {"num": "155311", "en": "Jaankari RTI application line – file an RTI by phone (BSNL premium-rate call; enquiry line 155310)", "hi": "जानकारी आरटीआई आवेदन लाइन – फ़ोन से आरटीआई दायर करें (बीएसएनएल प्रीमियम दर कॉल; पूछताछ लाइन 155310)"}] },
  { id: "chandigarh", type: "ut", en: "Chandigarh", hi: "चंडीगढ़", crs: true,
    codes: [], aliases: ["Chandigarh UT", "UT Chandigarh", "चण्डीगढ़", "ਚੰਡੀਗੜ੍ਹ"],
    cities: [{"en": "Chandigarh", "hi": "चंडीगढ़"}, {"en": "Manimajra", "hi": "मनीमाजरा"}, {"en": "Burail", "hi": "बुड़ैल"}, {"en": "Maloya", "hi": "मलोया"}, {"en": "Dhanas", "hi": "धनास"}, {"en": "Mauli Jagran", "hi": "मौली जागरां"}],
    links: [
      { c: "services", u: "http://chdservices.gov.in/", n: "e-District Chandigarh (chdservices)", nh: "ई-डिस्ट्रिक्ट चंडीगढ़" },
      { c: "ration", u: "https://chdfood.gov.in/", n: "Department of Food & Supplies and Consumer Affairs, Chandigarh", nh: "खाद्य एवं आपूर्ति तथा उपभोक्ता मामले विभाग, चंडीगढ़" },
      { c: "grievance", u: "https://loksamadhan.chd.gov.in/", n: "Lok Samadhan Chandigarh (Unified Online Grievance Monitoring System)", nh: "लोक समाधान चंडीगढ़ (एकीकृत ऑनलाइन शिकायत निगरानी प्रणाली)" },
      { c: "portal", u: "https://chandigarh.gov.in/", n: "The Official Website of the Chandigarh Administration", nh: "चंडीगढ़ प्रशासन की आधिकारिक वेबसाइट" },
    ],
    help: [] },
  { id: "chhattisgarh", type: "state", en: "Chhattisgarh", hi: "छत्तीसगढ़", crs: true,
    codes: ["CG"], aliases: ["Chattisgadh", "Chattisgarh", "Chhatisgarh", "Chhattisgad", "Chhattisgarh", "छ.ग.", "छत्तीसगढ़", "सीजी"],
    cities: [{"en": "Raipur", "hi": "रायपुर"}, {"en": "Nava Raipur (Atal Nagar)", "hi": "नवा रायपुर (अटल नगर)"}, {"en": "Bhilai", "hi": "भिलाई"}, {"en": "Durg", "hi": ""}, {"en": "Korba", "hi": "कोरबा"}, {"en": "Rajnandgaon", "hi": "राजनांदगांव"}, {"en": "Jagdalpur", "hi": "जगदलपुर"}, {"en": "Raigarh", "hi": "रायगढ़"}, {"en": "Ambikapur", "hi": "अंबिकापुर"}],
    links: [
      { c: "services", u: "https://sewasetu.cgstate.gov.in/home", n: "Seva Setu", nh: "सेवा सेतु" },
      { c: "land", u: "https://bhuiyan.cg.nic.in/", n: "Bhuiyan", nh: "भुइयाँ" },
      { c: "ration", u: "https://khadya.cg.nic.in/", n: "Food Department Chhattisgarh (Khadya)", nh: "खाद्य विभाग छत्तीसगढ़" },
      { c: "grievance", u: "https://cmhelpline.cg.gov.in/", n: "CM Helpline 1076", nh: "मुख्यमंत्री हेल्पलाइन 1076" },
      { c: "rti", u: "https://rtionline.cg.gov.in/", n: "RTI Online Chhattisgarh", nh: "आरटीआई ऑनलाइन छत्तीसगढ़" },
      { c: "portal", u: "https://cgstate.gov.in/", n: "Chhattisgarh Government Portal", nh: "छत्तीसगढ़ शासन पोर्टल" },
    ],
    help: [{"num": "1076", "en": "CM Helpline (public grievances)", "hi": "मुख्यमंत्री हेल्पलाइन (जन शिकायत)"}] },
  { id: "dadra-and-nagar-haveli-and-daman-and-diu", type: "ut", en: "Dadra and Nagar Haveli and Daman and Diu", hi: "दादरा और नगर हवेली और दमन और दीव", crs: true,
    codes: ["DNH"], aliases: ["DNH and DD", "DNH&DD", "DNHDD", "Dadra Nagar Haveli", "Dadra and Nagar Haveli", "Daman & Diu", "Daman and Diu", "Silvassa", "दमण और दीव", "दमन दीव", "दादरा नगर हवेली", "दानह"],
    cities: [{"en": "Silvassa", "hi": "सिलवासा"}, {"en": "Daman", "hi": ""}, {"en": "Diu", "hi": "दीव"}, {"en": "Dadra", "hi": "दादरा"}, {"en": "Naroli", "hi": "नरोली"}, {"en": "Khanvel", "hi": "खानवेल"}],
    links: [
      { c: "services", u: "https://sugam.dddgov.in/", n: "Sugam – Online Citizen Services (Revenue Department)", nh: "सुगम – ऑनलाइन नागरिक सेवाएँ (राजस्व विभाग)" },
      { c: "land", u: "https://sugam.dddgov.in/", n: "Sugam – Copy of RoR / Form I & XIV (Revenue Department)", nh: "सुगम – भूमि अभिलेख (RoR)" },
      { c: "rti", u: "https://rti.dddgov.in/login", n: "Right to Information – DNHDD (Online RTI Application)", nh: "सूचना का अधिकार पोर्टल – डीएनएचडीडी" },
      { c: "portal", u: "https://ddd.gov.in/", n: "UT of Dadra and Nagar Haveli and Daman and Diu – Official Portal", nh: "दादरा और नगर हवेली और दमन और दीव संघ प्रदेश पोर्टल" },
    ],
    help: [] },
  { id: "delhi", type: "ut", en: "Delhi", hi: "दिल्ली", crs: false,
    codes: [], aliases: ["Dehli", "Delhi", "Dilli", "GNCTD", "NCT Delhi", "NCT of Delhi", "National Capital Territory of Delhi", "New Delhi", "दिल्ली", "दिल्ली सरकार", "नई दिल्ली", "राष्ट्रीय राजधानी क्षेत्र दिल्ली"],
    cities: [{"en": "New Delhi", "hi": "नई दिल्ली"}, {"en": "Shahdara", "hi": "शाहदरा"}, {"en": "Narela", "hi": "नरेला"}, {"en": "Najafgarh", "hi": "नजफगढ़"}, {"en": "Karol Bagh", "hi": "करोल बाग"}, {"en": "Mehrauli", "hi": "महरौली"}, {"en": "Daryaganj", "hi": "दरियागंज"}],
    links: [
      { c: "services", u: "https://edistrict.delhi.gov.in/", n: "e-District Delhi", nh: "ई-डिस्ट्रिक्ट दिल्ली" },
      { c: "land", u: "https://dlrc.delhi.gov.in/", n: "Indraprastha Bhulekh (DLRC)", nh: "इंद्रप्रस्थ भू-लेख" },
      { c: "ration", u: "https://nfs.delhigovt.nic.in/", n: "NFS Delhi (Food Security Portal)", nh: "एनएफएस दिल्ली (खाद्य सुरक्षा पोर्टल)" },
      { c: "birth", u: "https://mcdonline.nic.in/portal/", n: "MCD Online (Birth & Death Registration)", nh: "एमसीडी ऑनलाइन (जन्म एवं मृत्यु पंजीकरण)" },
      { c: "grievance", u: "https://pgms.delhi.gov.in/", n: "PGMS Delhi (Public Grievance Monitoring System)", nh: "पीजीएमएस दिल्ली (लोक शिकायत निगरानी प्रणाली)" },
      { c: "rti", u: "https://rtionline.delhi.gov.in/", n: "RTI Online Delhi", nh: "आरटीआई ऑनलाइन दिल्ली" },
      { c: "portal", u: "https://delhi.gov.in/", n: "Delhi Government Portal", nh: "दिल्ली सरकार पोर्टल" },
    ],
    help: [{"num": "1076", "en": "Delhi Government doorstep delivery of public services helpline", "hi": "दिल्ली सरकार डोरस्टेप डिलीवरी (सार्वजनिक सेवाएं) हेल्पलाइन"}] },
  { id: "goa", type: "state", en: "Goa", hi: "गोवा", crs: false,
    codes: [], aliases: ["Goa State", "Gomantak", "गोमंतक", "गोवा"],
    cities: [{"en": "Panaji", "hi": "पणजी"}, {"en": "Margao (Madgaon)", "hi": "मडगांव"}, {"en": "Vasco da Gama", "hi": "वास्को-द-गामा"}, {"en": "Mapusa", "hi": "मापुसा"}, {"en": "Ponda", "hi": "पोंडा"}, {"en": "Bicholim", "hi": "बिचोलिम"}],
    links: [
      { c: "services", u: "https://goaonline.gov.in/", n: "Goa Online", nh: "गोवा ऑनलाइन" },
      { c: "land", u: "https://dslr.goa.gov.in/", n: "Directorate of Settlement & Land Records (DSLR) Goa", nh: "भू-अभिलेख एवं बंदोबस्त निदेशालय, गोवा" },
      { c: "ration", u: "https://goacivilsupplies.gov.in/", n: "Department of Civil Supplies & Consumer Affairs, Goa", nh: "नागरिक आपूर्ति एवं उपभोक्ता मामले विभाग, गोवा" },
      { c: "grievance", u: "https://goaonline.gov.in/Appln/Uil/DeptServices?__DocId=PGR&__ServiceId=PGR26", n: "Goa Online – Grievance Registration (Directorate of Public Grievances)", nh: "गोवा ऑनलाइन – शिकायत पंजीकरण (लोक शिकायत निदेशालय)" },
      { c: "rti", u: "https://rtionline.goa.gov.in/", n: "RTI Online Goa", nh: "आरटीआई ऑनलाइन गोवा" },
      { c: "portal", u: "https://www.goa.gov.in/", n: "Government of Goa Official Portal", nh: "गोवा सरकार पोर्टल" },
    ],
    help: [{"num": "+91-9319334335", "en": "Public Grievances Department helpline (Mon–Fri, 9:30 AM–5:45 PM)", "hi": "लोक शिकायत विभाग हेल्पलाइन (सोम–शुक्र, सुबह 9:30–शाम 5:45)"}, {"num": "1800-233-0022", "en": "Ration / Public Distribution System helpdesk", "hi": "राशन / सार्वजनिक वितरण प्रणाली हेल्पडेस्क"}, {"num": "+91-8882988000", "en": "Goa Online portal technical assistance (Mon–Fri office hours)", "hi": "गोवा ऑनलाइन पोर्टल तकनीकी सहायता (सोम–शुक्र कार्यालय समय)"}] },
  { id: "gujarat", type: "state", en: "Gujarat", hi: "गुजरात", crs: false,
    codes: ["GJ"], aliases: ["Gujarat State", "Gujarath", "Gujrat", "गुजरात", "ગુજરાત"],
    cities: [{"en": "Ahmedabad", "hi": "अहमदाबाद"}, {"en": "Vadodara", "hi": "वडोदरा"}, {"en": "Rajkot", "hi": "राजकोट"}, {"en": "Gandhinagar", "hi": "गांधीनगर"}, {"en": "Bhavnagar", "hi": "भावनगर"}, {"en": "Jamnagar", "hi": "जामनगर"}, {"en": "Junagadh", "hi": "जूनागढ़"}, {"en": "Bhuj", "hi": "भुज"}, {"en": "", "hi": "आणंद"}, {"en": "Baroda", "hi": "बड़ौदा"}],
    links: [
      { c: "services", u: "https://www.digitalgujarat.gov.in/", n: "Digital Gujarat", nh: "डिजिटल गुजरात" },
      { c: "land", u: "https://anyror.gujarat.gov.in/", n: "AnyROR (e-Dhara land records)", nh: "एनीआरओआर" },
      { c: "ration", u: "https://dcs-dof.gujarat.gov.in/", n: "Directorate of Food and Civil Supplies, Gujarat", nh: "अन्न एवं नागरिक आपूर्ति निदेशालय, गुजरात" },
      { c: "grievance", u: "https://swagat.gujarat.gov.in/", n: "SWAGAT Online (CM's grievance redressal)", nh: "स्वागत ऑनलाइन" },
      { c: "portal", u: "https://gujaratindia.gov.in/", n: "Gujarat Government Portal", nh: "गुजरात सरकार पोर्टल" },
    ],
    help: [{"num": "1800-233-5500", "en": "Digital Gujarat helpdesk / Food & Civil Supplies (ration) toll-free helpline", "hi": "डिजिटल गुजरात हेल्पडेस्क / अन्न एवं नागरिक आपूर्ति (राशन) टोल-फ्री हेल्पलाइन"}] },
  { id: "haryana", type: "state", en: "Haryana", hi: "हरियाणा", crs: true,
    codes: [], aliases: ["Hariyana", "Haryana State", "हरयाणा"],
    cities: [{"en": "Faridabad", "hi": "फ़रीदाबाद"}, {"en": "Gurugram", "hi": "गुरुग्राम"}, {"en": "Panipat", "hi": "पानीपत"}, {"en": "Ambala", "hi": "अंबाला"}, {"en": "Rohtak", "hi": "रोहतक"}, {"en": "Hisar", "hi": "हिसार"}, {"en": "Karnal", "hi": "करनाल"}, {"en": "Sonipat", "hi": "सोनीपत"}, {"en": "Panchkula", "hi": "पंचकूला"}, {"en": "Yamunanagar", "hi": "यमुनानगर"}, {"en": "Gurgaon", "hi": "गुड़गांव"}],
    links: [
      { c: "services", u: "https://saralharyana.gov.in/", n: "Antyodaya SARAL Haryana", nh: "अंत्योदय सरल हरियाणा" },
      { c: "land", u: "https://jamabandi.nic.in/", n: "Jamabandi Haryana", nh: "जमाबंदी हरियाणा" },
      { c: "ration", u: "https://haryanafood.gov.in/", n: "Food, Civil Supplies & Consumer Affairs Department Haryana", nh: "खाद्य, नागरिक आपूर्ति एवं उपभोक्ता मामले विभाग, हरियाणा" },
      { c: "grievance", u: "https://cmharyanacell.nic.in/", n: "CM Window Haryana", nh: "सीएम विंडो हरियाणा" },
      { c: "rti", u: "https://rtiharyana.gov.in/", n: "Haryana RTI Online Portal", nh: "हरियाणा आरटीआई ऑनलाइन पोर्टल" },
      { c: "portal", u: "https://www.haryana.gov.in/", n: "Haryana Government Official Portal", nh: "हरियाणा सरकार का आधिकारिक पोर्टल" },
    ],
    help: [{"num": "1800-2000-023", "en": "Antyodaya SARAL helpline for schemes/services queries", "hi": "अंत्योदय सरल हेल्पलाइन (योजनाओं/सेवाओं संबंधी प्रश्न)"}, {"num": "1800-180-2087", "en": "Haryana PDS / consumer toll-free helpline (Food & Supplies Dept)", "hi": "हरियाणा पीडीएस/उपभोक्ता टोल-फ्री हेल्पलाइन (खाद्य एवं आपूर्ति विभाग)"}, {"num": "1967", "en": "Haryana PDS helpline (Food & Supplies Dept)", "hi": "हरियाणा पीडीएस हेल्पलाइन (खाद्य एवं आपूर्ति विभाग)"}] },
  { id: "himachal-pradesh", type: "state", en: "Himachal Pradesh", hi: "हिमाचल प्रदेश", crs: true,
    codes: ["HP"], aliases: ["Himachal", "हि.प्र.", "हिमाचल"],
    cities: [{"en": "Shimla", "hi": "शिमला"}, {"en": "Dharamshala", "hi": "धर्मशाला"}, {"en": "Solan", "hi": "सोलन"}, {"en": "Kullu", "hi": "कुल्लू"}, {"en": "Hamirpur", "hi": "हमीरपुर"}, {"en": "Chamba", "hi": "चंबा"}, {"en": "Nahan", "hi": "नाहन"}, {"en": "Simla", "hi": ""}],
    links: [
      { c: "services", u: "https://himseva.hp.gov.in/", n: "Him Seva (HimSeva Portal, formerly e-District Himachal Pradesh)", nh: "हिम सेवा पोर्टल (पूर्व में ई-डिस्ट्रिक्ट हिमाचल प्रदेश)" },
      { c: "land", u: "https://himbhoomilmk.nic.in/viewlandrecords.aspx", n: "HimBhoomi", nh: "हिमभूमि" },
      { c: "ration", u: "https://food.hp.nic.in/", n: "Food, Civil Supplies & Consumer Affairs Department, Himachal Pradesh", nh: "खाद्य, नागरिक आपूर्ति एवं उपभोक्ता मामले विभाग, हिमाचल प्रदेश" },
      { c: "grievance", u: "https://esamadhan.nic.in/", n: "Samgr eSamadhan (Himachal Pradesh Public Grievance Portal)", nh: "समग्र ई-समाधान (हिमाचल प्रदेश जन शिकायत पोर्टल)" },
      { c: "rti", u: "https://onlinerti.hp.gov.in/", n: "Online RTI Himachal Pradesh", nh: "ऑनलाइन आरटीआई हिमाचल प्रदेश" },
      { c: "portal", u: "https://himachal.gov.in/", n: "Official Web Portal of Government of Himachal Pradesh", nh: "हिमाचल प्रदेश सरकार का आधिकारिक वेब पोर्टल" },
    ],
    help: [{"num": "1100", "en": "Mukhya Mantri Sewa Sankalp Helpline (CM grievance helpline)", "hi": "मुख्यमंत्री सेवा संकल्प हेल्पलाइन (मुख्यमंत्री शिकायत हेल्पलाइन)"}] },
  { id: "jammu-and-kashmir", type: "ut", en: "Jammu and Kashmir", hi: "जम्मू और कश्मीर", crs: true,
    codes: ["J&K", "JK"], aliases: ["J and K", "Jammu & Kashmir", "Jammu Kashmir", "Kashmir", "जम्मू कश्मीर", "जम्मू-कश्मीर", "जे एंड के"],
    cities: [{"en": "Srinagar", "hi": "श्रीनगर"}, {"en": "Jammu", "hi": "जम्मू"}, {"en": "Anantnag", "hi": "अनंतनाग"}, {"en": "Baramulla", "hi": "बारामूला"}, {"en": "Sopore", "hi": "सोपोर"}, {"en": "Udhampur", "hi": "उधमपुर"}, {"en": "Kathua", "hi": "कठुआ"}, {"en": "Rajouri", "hi": "राजौरी"}, {"en": "Poonch", "hi": "पुंछ"}, {"en": "Doda", "hi": "डोडा"}],
    links: [
      { c: "services", u: "https://jansugam.jk.gov.in/", n: "Jan Sugam", nh: "जन सुगम" },
      { c: "land", u: "https://landrecords.jk.gov.in/", n: "Aapki Zameen Aapki Nigrani (J&K Land Records Information System)", nh: "आपकी ज़मीन आपकी निगरानी (जम्मू-कश्मीर भूमि अभिलेख सूचना प्रणाली)" },
      { c: "ration", u: "https://rcms.jk.gov.in/", n: "RCMS J&K (Ration Card Management System)", nh: "आरसीएमएस जम्मू-कश्मीर (राशन कार्ड प्रबंधन प्रणाली)" },
      { c: "grievance", u: "https://samadhan.jk.gov.in/", n: "JK Samadhan", nh: "जेके समाधान" },
      { c: "rti", u: "https://rtionline.jk.gov.in/", n: "J&K RTI Online", nh: "जम्मू-कश्मीर आरटीआई ऑनलाइन" },
      { c: "portal", u: "https://jk.gov.in/jammukashmir/", n: "Official Portal of the UT of Jammu and Kashmir", nh: "जम्मू और कश्मीर केंद्र शासित प्रदेश का आधिकारिक पोर्टल" },
    ],
    help: [{"num": "1905", "en": "JK Samadhan public grievance helpline", "hi": "जेके समाधान जन शिकायत हेल्पलाइन"}] },
  { id: "jharkhand", type: "state", en: "Jharkhand", hi: "झारखंड", crs: true,
    codes: ["JH"], aliases: ["Jharkand", "Jharkhand State", "झारखंड", "झारखण्ड"],
    cities: [{"en": "Ranchi", "hi": "रांची"}, {"en": "Jamshedpur", "hi": "जमशेदपुर"}, {"en": "Dhanbad", "hi": "धनबाद"}, {"en": "Bokaro Steel City", "hi": "बोकारो स्टील सिटी"}, {"en": "Deoghar", "hi": "देवघर"}, {"en": "Hazaribagh", "hi": "हज़ारीबाग"}, {"en": "Giridih", "hi": "गिरिडीह"}, {"en": "Dumka", "hi": "दुमका"}, {"en": "Ramgarh", "hi": "रामगढ़"}, {"en": "Medininagar (Daltonganj)", "hi": "मेदिनीनगर (डालटनगंज)"}],
    links: [
      { c: "services", u: "https://jharsewa.jharkhand.gov.in/", n: "JharSewa", nh: "झारसेवा" },
      { c: "land", u: "https://jharbhoomi.jharkhand.gov.in/", n: "Jharbhoomi", nh: "झारभूमि" },
      { c: "ration", u: "https://aahar.jharkhand.gov.in/", n: "Aahar Jharkhand", nh: "आहार झारखंड" },
      { c: "rti", u: "https://rti.jharkhand.gov.in/", n: "Jharkhand Online RTI Portal", nh: "झारखंड ऑनलाइन आरटीआई पोर्टल" },
      { c: "portal", u: "https://www.jharkhand.gov.in/", n: "Jharkhand State Portal", nh: "झारखंड राज्य पोर्टल" },
    ],
    help: [] },
  { id: "karnataka", type: "state", en: "Karnataka", hi: "कर्नाटक", crs: false,
    codes: [], aliases: ["Karnatak", "Karnatka", "Mysore State", "कर्नाटका"],
    cities: [{"en": "Bengaluru", "hi": "बेंगलुरु"}, {"en": "Mysuru", "hi": "मैसूरु"}, {"en": "Mangaluru", "hi": "मंगलुरु"}, {"en": "Hubballi", "hi": "हुब्बल्ली"}, {"en": "Belagavi", "hi": "बेलगावी"}, {"en": "Kalaburagi", "hi": "कलबुर्गी"}, {"en": "Davanagere", "hi": "दावणगेरे"}, {"en": "Ballari", "hi": "बल्लारी"}, {"en": "Shivamogga", "hi": "शिवमोग्गा"}, {"en": "Tumakuru", "hi": "तुमकुरु"}, {"en": "Bangalore", "hi": "बैंगलोर"}, {"en": "Mysore", "hi": "मैसूर"}, {"en": "Mangalore", "hi": "मंगलौर"}, {"en": "Hubli", "hi": "हुबली"}, {"en": "Belgaum", "hi": "बेलगाम"}],
    links: [
      { c: "services", u: "https://sevasindhu.karnataka.gov.in/", n: "Seva Sindhu", nh: "सेवा सिंधु" },
      { c: "land", u: "https://landrecords.karnataka.gov.in/", n: "Bhoomi (Land Records)", nh: "भूमि (भू-अभिलेख)" },
      { c: "ration", u: "https://ahara.karnataka.gov.in/", n: "Ahara (Food, Civil Supplies & Consumer Affairs)", nh: "आहार (खाद्य एवं नागरिक आपूर्ति विभाग)" },
      { c: "birth", u: "https://ejanma.karnataka.gov.in/", n: "eJanMa (Births and Deaths)", nh: "ई-जनमा (जन्म एवं मृत्यु)" },
      { c: "grievance", u: "https://ipgrs.karnataka.gov.in/", n: "Janaspandana iPGRS", nh: "जनस्पंदन आईपीजीआरएस" },
      { c: "rti", u: "https://rtionline.karnataka.gov.in/", n: "RTI Online Karnataka", nh: "आरटीआई ऑनलाइन कर्नाटक" },
      { c: "portal", u: "https://www.karnataka.gov.in/", n: "Government of Karnataka", nh: "कर्नाटक सरकार" },
    ],
    help: [{"num": "1902", "en": "Janaspandana iPGRS public grievance helpline", "hi": "जनस्पंदन आईपीजीआरएस जन शिकायत हेल्पलाइन"}] },
  { id: "kerala", type: "state", en: "Kerala", hi: "केरल", crs: false,
    codes: ["KL"], aliases: ["Keralam", "Kerela", "केरलम", "केरला"],
    cities: [{"en": "Thiruvananthapuram", "hi": "तिरुवनंतपुरम"}, {"en": "Kochi", "hi": "कोच्चि"}, {"en": "Kozhikode", "hi": "कोझिकोड"}, {"en": "Thrissur", "hi": "त्रिशूर"}, {"en": "Kollam", "hi": "कोल्लम"}, {"en": "Kannur", "hi": "कन्नूर"}, {"en": "Alappuzha", "hi": "अलप्पुझा"}, {"en": "Palakkad", "hi": "पालक्काड"}, {"en": "Kottayam", "hi": "कोट्टायम"}, {"en": "Malappuram", "hi": "मलप्पुरम"}, {"en": "Trivandrum", "hi": "त्रिवेंद्रम"}, {"en": "Cochin", "hi": "कोचीन"}, {"en": "Calicut", "hi": "कालीकट"}],
    links: [
      { c: "services", u: "https://edistrict.kerala.gov.in/", n: "e-District Kerala", nh: "ई-डिस्ट्रिक्ट केरल" },
      { c: "land", u: "https://revenue.kerala.gov.in/", n: "Revenue eServices (ReLIS)", nh: "राजस्व ई-सेवाएँ (रेलिस)" },
      { c: "ration", u: "https://civilsupplieskerala.gov.in/", n: "Civil Supplies Kerala", nh: "सिविल सप्लाइज़ केरल" },
      { c: "birth", u: "https://ksmart.lsgkerala.gov.in/", n: "K-SMART", nh: "के-स्मार्ट" },
      { c: "grievance", u: "https://cmo.kerala.gov.in/", n: "CM's Public Grievance Redressal Cell (CMO Portal)", nh: "मुख्यमंत्री जन शिकायत निवारण प्रकोष्ठ (सीएमओ पोर्टल)" },
      { c: "rti", u: "https://rtiportal.kerala.gov.in/", n: "RTI Portal Kerala", nh: "आरटीआई पोर्टल केरल" },
      { c: "portal", u: "https://kerala.gov.in/", n: "Government of Kerala", nh: "केरल सरकार" },
    ],
    help: [{"num": "1076", "en": "Chief Minister's Public Grievance Redressal Cell (toll-free)", "hi": "मुख्यमंत्री जन शिकायत निवारण प्रकोष्ठ (टोल-फ्री)"}] },
  { id: "ladakh", type: "ut", en: "Ladakh", hi: "लद्दाख", crs: true,
    codes: [], aliases: ["Ladakh UT", "Leh Ladakh", "Leh-Ladakh", "लदाख", "लद्दाख केंद्र शासित प्रदेश"],
    cities: [{"en": "Leh", "hi": "लेह"}, {"en": "Kargil", "hi": "कारगिल"}, {"en": "Drass", "hi": "द्रास"}, {"en": "Padum", "hi": "पदुम"}, {"en": "Diskit", "hi": "दिस्कित"}, {"en": "Nyoma", "hi": "न्योमा"}],
    links: [
      { c: "services", u: "https://domicile.ladakh.gov.in/", n: "Domicile Ladakh (Online Ladakh Domicile Certificate Portal)", nh: "डोमिसाइल लद्दाख (ऑनलाइन लद्दाख अधिवास प्रमाण पत्र पोर्टल)" },
      { c: "land", u: "https://landrecords.ladakh.gov.in/", n: "Ladakh Land Records (LaLR)", nh: "लद्दाख भूमि अभिलेख (LaLR)" },
      { c: "grievance", u: "https://grievance.ladakh.gov.in/", n: "Ladakh Integrated Grievance Redressal and Monitoring System (IGRMS)", nh: "लद्दाख एकीकृत शिकायत निवारण एवं निगरानी प्रणाली" },
      { c: "rti", u: "https://rtionline.ladakh.gov.in/", n: "RTI Online Ladakh", nh: "आरटीआई ऑनलाइन लद्दाख" },
      { c: "portal", u: "https://ladakh.gov.in/", n: "The Administration of Union Territory of Ladakh", nh: "लद्दाख केंद्र शासित प्रदेश प्रशासन" },
    ],
    help: [] },
  { id: "lakshadweep", type: "ut", en: "Lakshadweep", hi: "लक्षद्वीप", crs: true,
    codes: [], aliases: ["Laccadive Islands", "Laccadives", "Lakshadeep", "Lakshadwip", "Lakshdweep", "लक्षद्वीप", "लक्ष्यद्वीप"],
    cities: [{"en": "Kavaratti", "hi": "कवरत्ती"}, {"en": "Agatti", "hi": "अगाती"}, {"en": "Minicoy", "hi": "मिनीकॉय"}, {"en": "Amini", "hi": "अमीनी"}, {"en": "Andrott", "hi": "एंड्रोट"}, {"en": "Kalpeni", "hi": "कलपेनी"}, {"en": "Kadmat", "hi": "कड़मठ"}, {"en": "Kiltan", "hi": "किल्तान"}],
    links: [
      { c: "services", u: "https://edistrict.utl.gov.in/", n: "e-District Lakshadweep", nh: "ई-डिस्ट्रिक्ट लक्षद्वीप" },
      { c: "ration", u: "https://lakpds.gov.in/", n: "Public Distribution System Portal – Food & Civil Supplies Department, Lakshadweep", nh: "सार्वजनिक वितरण प्रणाली पोर्टल, लक्षद्वीप" },
      { c: "portal", u: "https://lakshadweep.gov.in/", n: "U.T. Administration of Lakshadweep – Official Website", nh: "लक्षद्वीप प्रशासन पोर्टल" },
    ],
    help: [{"num": "1800-425-3186", "en": "PDS / ration toll-free helpline", "hi": "राशन / सार्वजनिक वितरण प्रणाली टोल-फ्री हेल्पलाइन"}] },
  { id: "madhya-pradesh", type: "state", en: "Madhya Pradesh", hi: "मध्य प्रदेश", crs: true,
    codes: ["MP"], aliases: ["Madhya Pardesh", "Madhya Pradesh", "Madhyapradesh", "एमपी", "म.प्र.", "मध्य प्रदेश", "मध्यप्रदेश"],
    cities: [{"en": "Bhopal", "hi": "भोपाल"}, {"en": "Indore", "hi": "इंदौर"}, {"en": "Jabalpur", "hi": "जबलपुर"}, {"en": "Gwalior", "hi": "ग्वालियर"}, {"en": "Ujjain", "hi": "उज्जैन"}, {"en": "Rewa", "hi": "रीवा"}, {"en": "Satna", "hi": "सतना"}, {"en": "Ratlam", "hi": "रतलाम"}, {"en": "Dewas", "hi": "देवास"}],
    links: [
      { c: "services", u: "https://eseva.mp.gov.in/", n: "MP e-Seva", nh: "एमपी ई-सेवा" },
      { c: "land", u: "https://mpbhulekh.gov.in/", n: "MP Bhulekh", nh: "एमपी भूलेख" },
      { c: "ration", u: "https://rationmitra.nic.in/", n: "Ration Mitra (MP State Food Security Portal)", nh: "राशन मित्र" },
      { c: "grievance", u: "https://cmhelpline.mp.gov.in/", n: "CM Helpline 181 (MP Samadhan)", nh: "सीएम हेल्पलाइन 181" },
      { c: "rti", u: "https://rti.mp.gov.in/", n: "RTI MP Online Portal", nh: "आरटीआई एमपी ऑनलाइन पोर्टल" },
      { c: "portal", u: "https://mp.gov.in/", n: "Madhya Pradesh State Portal", nh: "मध्य प्रदेश शासन पोर्टल" },
    ],
    help: [{"num": "181", "en": "CM Helpline (public grievances)", "hi": "मुख्यमंत्री हेल्पलाइन (जन शिकायत)"}] },
  { id: "maharashtra", type: "state", en: "Maharashtra", hi: "महाराष्ट्र", crs: true,
    codes: ["MH"], aliases: ["Maharashtr", "Maharashtra State", "Maharastra", "महाराष्ट्र"],
    cities: [{"en": "Mumbai", "hi": "मुंबई"}, {"en": "Pune", "hi": "पुणे"}, {"en": "Nagpur", "hi": "नागपुर"}, {"en": "Nashik", "hi": "नासिक"}, {"en": "Chhatrapati Sambhajinagar (Aurangabad)", "hi": "छत्रपति संभाजीनगर"}, {"en": "", "hi": "ठाणे"}, {"en": "Solapur", "hi": "सोलापुर"}, {"en": "Kolhapur", "hi": "कोल्हापुर"}, {"en": "Amravati", "hi": "अमरावती"}, {"en": "Nanded", "hi": "नांदेड़"}, {"en": "Bombay", "hi": "बंबई"}, {"en": "Poona", "hi": ""}],
    links: [
      { c: "services", u: "https://aaplesarkar.mahaonline.gov.in/", n: "Aaple Sarkar", nh: "आपले सरकार" },
      { c: "land", u: "https://mahabhumi.gov.in/mahabhumilink", n: "Mahabhumi (Portal for Land Records Services)", nh: "महाभूमि" },
      { c: "ration", u: "https://rcms.mahafood.gov.in/", n: "RCMS – Ration Card Management System (Mahafood)", nh: "राशन कार्ड प्रबंधन प्रणाली (महाफूड)" },
      { c: "grievance", u: "https://grievances.maharashtra.gov.in/en", n: "Aaple Sarkar Grievance Redressal Portal", nh: "आपले सरकार शिकायत निवारण पोर्टल" },
      { c: "rti", u: "https://rtionline.maharashtra.gov.in/", n: "RTI Online Maharashtra", nh: "आरटीआई ऑनलाइन महाराष्ट्र" },
      { c: "portal", u: "https://maharashtra.gov.in/", n: "Maharashtra Government Portal", nh: "महाराष्ट्र शासन पोर्टल" },
    ],
    help: [{"num": "1800-120-8040", "en": "Aaple Sarkar 24x7 Citizen Call Center (toll-free)", "hi": "आपले सरकार 24x7 नागरिक कॉल सेंटर (टोल-फ्री)"}, {"num": "1800-22-4950", "en": "Ration / Public Distribution System helpdesk", "hi": "राशन / सार्वजनिक वितरण प्रणाली हेल्पडेस्क"}] },
  { id: "manipur", type: "state", en: "Manipur", hi: "मणिपुर", crs: false,
    codes: [], aliases: ["Kangleipak", "Manipur", "मणिपुर", "मनिपुर"],
    cities: [{"en": "Imphal", "hi": "इम्फाल"}, {"en": "Thoubal", "hi": "थौबल"}, {"en": "Bishnupur", "hi": "बिष्णुपुर"}, {"en": "Churachandpur", "hi": "चुराचांदपुर"}, {"en": "Kakching", "hi": "काकचिंग"}, {"en": "Ukhrul", "hi": "उखरुल"}, {"en": "Tamenglong", "hi": "तामेंगलोंग"}, {"en": "Jiribam", "hi": "जिरीबाम"}],
    links: [
      { c: "services", u: "https://esebamanipur.mn.gov.in/", n: "e-Seba Manipur", nh: "ई-सेबा मणिपुर" },
      { c: "land", u: "https://louchapathap.nic.in/", n: "Loucha Pathap (Manipur Land Records)", nh: "लौचा पथाप (मणिपुर भूमि अभिलेख)" },
      { c: "ration", u: "https://rcmsmanipur.nic.in/", n: "RCMS Manipur – Ration Card Management System", nh: "आरसीएमएस मणिपुर – राशन कार्ड प्रबंधन प्रणाली" },
      { c: "portal", u: "https://manipur.gov.in/", n: "Manipur State Portal", nh: "मणिपुर राज्य पोर्टल" },
    ],
    help: [] },
  { id: "meghalaya", type: "state", en: "Meghalaya", hi: "मेघालय", crs: true,
    codes: [], aliases: ["Meghalaya", "मेघालय"],
    cities: [{"en": "Shillong", "hi": "शिलांग"}, {"en": "", "hi": "तुरा"}, {"en": "Jowai", "hi": "जोवाई"}, {"en": "Nongpoh", "hi": "नोंगपोह"}, {"en": "Nongstoin", "hi": "नोंगस्टॉइन"}, {"en": "Williamnagar", "hi": "विलियमनगर"}, {"en": "Baghmara", "hi": "बाघमारा"}, {"en": "Khliehriat", "hi": "ख्लीहरियात"}, {"en": "Resubelpara", "hi": "रेसुबेलपारा"}, {"en": "Mawkyrwat", "hi": "मॉकिरवाट"}],
    links: [
      { c: "services", u: "https://megedistrict.gov.in/", n: "e-District Meghalaya", nh: "ई-डिस्ट्रिक्ट मेघालय" },
      { c: "ration", u: "https://megrcms.nic.in/", n: "MegRCMS – Ration Card Management System", nh: "मेघ आरसीएमएस – राशन कार्ड प्रबंधन प्रणाली" },
      { c: "rti", u: "https://megrti.gov.in/onlinerti", n: "Meghalaya RTI Online", nh: "मेघालय आरटीआई ऑनलाइन" },
      { c: "portal", u: "https://meghalaya.gov.in/", n: "Meghalaya State Portal", nh: "मेघालय राज्य पोर्टल" },
    ],
    help: [{"num": "1971", "en": "Meghalaya 'Connect' helpline for administrative help", "hi": "मेघालय 'कनेक्ट' हेल्पलाइन – प्रशासनिक सहायता"}, {"num": "1800-345-3644", "en": "Food & Civil Supplies (PDS/ration) toll-free helpdesk", "hi": "खाद्य एवं नागरिक आपूर्ति (राशन/पीडीएस) टोल-फ्री हेल्पडेस्क"}] },
  { id: "mizoram", type: "state", en: "Mizoram", hi: "मिज़ोरम", crs: true,
    codes: [], aliases: ["Lushai Hills", "Mizoram", "मिज़ोरम", "मिजोरम"],
    cities: [{"en": "Aizawl", "hi": "आइज़ोल"}, {"en": "Lunglei", "hi": "लुंगलेई"}, {"en": "Champhai", "hi": "चम्फाई"}, {"en": "Kolasib", "hi": "कोलासिब"}, {"en": "Serchhip", "hi": "सेरछिप"}, {"en": "Mamit", "hi": "मामित"}, {"en": "Lawngtlai", "hi": "लॉन्गतलाई"}, {"en": "Siaha", "hi": "सियाहा"}, {"en": "Saitual", "hi": "सैतुआल"}, {"en": "Khawzawl", "hi": "खॉज़ॉल"}],
    links: [
      { c: "services", u: "https://edistrict.mizoram.gov.in/", n: "e-District Mizoram", nh: "ई-डिस्ट्रिक्ट मिज़ोरम" },
      { c: "grievance", u: "https://mipuiaw.mizoram.gov.in/", n: "Mipui Aw (Public Grievance portal)", nh: "मिपुई ऑ (लोक शिकायत पोर्टल)" },
      { c: "portal", u: "https://mizoram.gov.in/", n: "Mizoram State Portal (Mizoram Sawrkar)", nh: "मिज़ोरम राज्य पोर्टल (मिज़ोरम सॉरकार)" },
    ],
    help: [] },
  { id: "nagaland", type: "state", en: "Nagaland", hi: "नागालैंड", crs: true,
    codes: [], aliases: ["Nagaland", "नगालैंड", "नागालैंड"],
    cities: [{"en": "Kohima", "hi": "कोहिमा"}, {"en": "Dimapur", "hi": "दीमापुर"}, {"en": "Mokokchung", "hi": "मोकोकचुंग"}, {"en": "Tuensang", "hi": "त्वेनसांग"}, {"en": "Wokha", "hi": "वोखा"}, {"en": "Zunheboto", "hi": "ज़ुन्हेबोटो"}, {"en": "", "hi": "मोन"}, {"en": "Kiphire", "hi": "किफिरे"}, {"en": "Peren", "hi": "पेरेन"}],
    links: [
      { c: "services", u: "https://services.nagaland.gov.in/", n: "Unified Services Portal (USP Nagaland)", nh: "यूनिफाइड सर्विसेज़ पोर्टल (यूएसपी नागालैंड)" },
      { c: "ration", u: "https://feast.nagaland.gov.in/", n: "FEAST Nagaland (ration card & entitlement lookup)", nh: "फीस्ट नागालैंड (राशन कार्ड एवं पात्रता जानकारी)" },
      { c: "grievance", u: "https://pgportal.gov.in/", n: "CPGRAMS (linked by Nagaland State Portal as 'Raise a Grievance')", nh: "सीपीग्राम्स (नागालैंड राज्य पोर्टल पर 'शिकायत दर्ज करें')" },
      { c: "portal", u: "https://nagaland.gov.in/", n: "Nagaland State Portal", nh: "नागालैंड राज्य पोर्टल" },
    ],
    help: [{"num": "1800-345-3704", "en": "Food & Civil Supplies (ration/PDS) grievance toll-free number", "hi": "खाद्य एवं नागरिक आपूर्ति (राशन/पीडीएस) शिकायत टोल-फ्री नंबर"}, {"num": "1800-345-3705", "en": "Food & Civil Supplies (ration/PDS) grievance toll-free number (second line)", "hi": "खाद्य एवं नागरिक आपूर्ति (राशन/पीडीएस) शिकायत टोल-फ्री नंबर (दूसरी लाइन)"}] },
  { id: "odisha", type: "state", en: "Odisha", hi: "ओडिशा", crs: false,
    codes: [], aliases: ["Odisa", "Orisa", "Orissa", "Utkal", "उड़ीसा", "ओड़िशा", "ओडिशा"],
    cities: [{"en": "Bhubaneswar", "hi": "भुवनेश्वर"}, {"en": "Cuttack", "hi": "कटक"}, {"en": "Rourkela", "hi": "राउरकेला"}, {"en": "Berhampur (Brahmapur)", "hi": "ब्रह्मपुर"}, {"en": "Sambalpur", "hi": "संबलपुर"}, {"en": "Balasore (Baleswar)", "hi": "बालेश्वर"}, {"en": "Bhadrak", "hi": "भद्रक"}, {"en": "Baripada", "hi": "बारीपदा"}, {"en": "Jharsuguda", "hi": "झारसुगुड़ा"}],
    links: [
      { c: "services", u: "https://edistrict.odisha.gov.in/", n: "eDistrict Odisha", nh: "ई-डिस्ट्रिक्ट ओडिशा" },
      { c: "land", u: "https://bhulekh.ori.nic.in/", n: "Bhulekh Odisha", nh: "भूलेख ओडिशा" },
      { c: "ration", u: "https://food.odisha.gov.in/", n: "Food Supplies & Consumer Welfare Department, Odisha", nh: "खाद्य आपूर्ति एवं उपभोक्ता कल्याण विभाग, ओडिशा" },
      { c: "birth", u: "https://www.birthdeath.odisha.gov.in/", n: "Birth and Death Odisha", nh: "जन्म और मृत्यु ओडिशा" },
      { c: "grievance", u: "https://janasunani.odisha.gov.in/", n: "Jana Sunani – Public Grievance Redressal Portal", nh: "जन सुनानी – लोक शिकायत निवारण पोर्टल" },
      { c: "rti", u: "https://www.rtiodisha.gov.in/", n: "RTI Odisha (RTI Central Monitoring Mechanism)", nh: "आरटीआई ओडिशा (केंद्रीय निगरानी तंत्र)" },
      { c: "portal", u: "https://odisha.gov.in/", n: "Odisha State Portal", nh: "ओडिशा राज्य पोर्टल" },
    ],
    help: [{"num": "6370951930", "en": "Jana Sunani WhatsApp – send 'Hi' to register or track a public grievance", "hi": "जन सुनानी व्हाट्सऐप – शिकायत दर्ज/स्थिति जानने हेतु 'Hi' भेजें", "wa": true}] },
  { id: "puducherry", type: "ut", en: "Puducherry", hi: "पुदुचेरी", crs: false,
    codes: [], aliases: ["Pondicherry", "Pondy", "पांडिचेरी", "पुडुचेरी", "पॉन्डिचेरी"],
    cities: [{"en": "Puducherry", "hi": "पुदुचेरी"}, {"en": "Karaikal", "hi": "कराईकल"}, {"en": "Mahe", "hi": "माहे"}, {"en": "Yanam", "hi": "यानम"}, {"en": "Ozhukarai", "hi": "ओझुकरई"}, {"en": "Villianur", "hi": "विल्लियनूर"}],
    links: [
      { c: "services", u: "https://edistrict.py.gov.in/", n: "e-District Puducherry", nh: "ई-डिस्ट्रिक्ट पुदुचेरी" },
      { c: "land", u: "https://nilamagal.py.gov.in/public/", n: "Nilamagal (Land Records)", nh: "निलमगल (भू-अभिलेख)" },
      { c: "ration", u: "https://pdsswo.py.gov.in/onlineservices", n: "PDS Online Services (Civil Supplies & Consumer Affairs)", nh: "पीडीएस ऑनलाइन सेवाएँ (नागरिक आपूर्ति एवं उपभोक्ता मामले)" },
      { c: "birth", u: "https://puduvaisevai.py.gov.in/", n: "Puduvai Sevai (Birth & Death Certificates)", nh: "पुदुवै सेवै (जन्म एवं मृत्यु प्रमाण पत्र)" },
      { c: "grievance", u: "https://lgredressal.py.gov.in/pgrs/", n: "LG's Petition Monitoring System", nh: "उपराज्यपाल याचिका निगरानी प्रणाली" },
      { c: "portal", u: "https://py.gov.in/", n: "Government of Puducherry", nh: "पुदुचेरी सरकार" },
    ],
    help: [{"num": "1800-425-1082", "en": "Civil Supplies (PDS) toll-free helpdesk", "hi": "नागरिक आपूर्ति (पीडीएस) टोल-फ्री हेल्पडेस्क"}, {"num": "1800-425-2260", "en": "e-District Puducherry toll-free helpline", "hi": "ई-डिस्ट्रिक्ट पुदुचेरी टोल-फ्री हेल्पलाइन"}] },
  { id: "punjab", type: "state", en: "Punjab", hi: "पंजाब", crs: false,
    codes: ["PB"], aliases: ["Panjab", "Punjab State", "ਪੰਜਾਬ"],
    cities: [{"en": "Ludhiana", "hi": "लुधियाना"}, {"en": "Amritsar", "hi": "अमृतसर"}, {"en": "Jalandhar", "hi": "जालंधर"}, {"en": "Patiala", "hi": "पटियाला"}, {"en": "Bathinda", "hi": "बठिंडा"}, {"en": "Mohali", "hi": "मोहाली"}, {"en": "Hoshiarpur", "hi": "होशियारपुर"}, {"en": "Pathankot", "hi": "पठानकोट"}, {"en": "Moga", "hi": "मोगा"}, {"en": "Firozpur", "hi": "फ़िरोज़पुर"}],
    links: [
      { c: "services", u: "https://digi.punjab.gov.in/", n: "DiGi Punjab (Unified Digital Platform for Citizen Services)", nh: "डिजी पंजाब (नागरिक सेवाओं के लिए एकीकृत डिजिटल प्लेटफ़ॉर्म)" },
      { c: "land", u: "https://jamabandi.punjab.gov.in/", n: "Punjab Land Records (Easy Jamabandi)", nh: "पंजाब लैंड रिकॉर्ड्स (ईज़ी जमाबंदी)" },
      { c: "ration", u: "http://foodsuppb.gov.in/", n: "Department of Food, Civil Supplies & Consumer Affairs, Punjab", nh: "खाद्य, नागरिक आपूर्ति एवं उपभोक्ता मामले विभाग, पंजाब" },
      { c: "grievance", u: "https://connect.punjab.gov.in/", n: "Connect Punjab (Punjab Grievance Redressal System)", nh: "कनेक्ट पंजाब (पंजाब शिकायत निवारण प्रणाली)" },
      { c: "rti", u: "https://rti.punjab.gov.in/", n: "RTI Punjab", nh: "आरटीआई पंजाब" },
      { c: "portal", u: "https://punjab.gov.in/", n: "Government of Punjab Official Portal", nh: "पंजाब सरकार का आधिकारिक पोर्टल" },
    ],
    help: [{"num": "1100", "en": "Punjab State Helpline (citizen services and grievances)", "hi": "पंजाब राज्य हेल्पलाइन (नागरिक सेवाएं एवं शिकायतें)"}] },
  { id: "rajasthan", type: "state", en: "Rajasthan", hi: "राजस्थान", crs: false,
    codes: ["RJ"], aliases: ["Rajasthan", "Rajputana", "Rajsthan", "रजस्थान", "राजस्थान"],
    cities: [{"en": "Jaipur", "hi": "जयपुर"}, {"en": "Jodhpur", "hi": "जोधपुर"}, {"en": "Udaipur", "hi": "उदयपुर"}, {"en": "Ajmer", "hi": "अजमेर"}, {"en": "Bikaner", "hi": "बीकानेर"}, {"en": "Alwar", "hi": "अलवर"}, {"en": "Bhilwara", "hi": "भीलवाड़ा"}, {"en": "Sikar", "hi": "सीकर"}, {"en": "Bharatpur", "hi": "भरतपुर"}],
    links: [
      { c: "services", u: "https://emitra.rajasthan.gov.in/", n: "e-Mitra", nh: "ई-मित्र" },
      { c: "land", u: "https://apnakhata.rajasthan.gov.in/", n: "Apna Khata (e-Dharti)", nh: "अपना खाता (ई-धरती)" },
      { c: "ration", u: "https://food.rajasthan.gov.in/", n: "Food & Civil Supplies Department, Rajasthan", nh: "खाद्य एवं नागरिक आपूर्ति विभाग, राजस्थान" },
      { c: "birth", u: "https://pehchan.rajasthan.gov.in/", n: "Pehchan (Rajasthan Civil Registration System)", nh: "पहचान (राजस्थान सिविल रजिस्ट्रेशन प्रणाली)" },
      { c: "grievance", u: "https://sampark.rajasthan.gov.in/", n: "Rajasthan Sampark", nh: "राजस्थान संपर्क" },
      { c: "rti", u: "https://rti.rajasthan.gov.in/", n: "RTI Rajasthan", nh: "सूचना का अधिकार पोर्टल राजस्थान" },
      { c: "portal", u: "https://rajasthan.gov.in/", n: "Rajasthan State Portal", nh: "राजस्थान राज्य पोर्टल" },
    ],
    help: [{"num": "181", "en": "Rajasthan Sampark helpline (public grievances)", "hi": "राजस्थान संपर्क हेल्पलाइन (जन शिकायत)"}] },
  { id: "sikkim", type: "state", en: "Sikkim", hi: "सिक्किम", crs: true,
    codes: [], aliases: ["Sikkim State", "सिक्किम"],
    cities: [{"en": "Gangtok", "hi": "गंगटोक"}, {"en": "Namchi", "hi": "नामची"}, {"en": "Gyalshing", "hi": "ग्यालशिंग"}, {"en": "Mangan", "hi": "मंगन"}, {"en": "Pakyong", "hi": "पाकयोंग"}, {"en": "Soreng", "hi": "सोरेंग"}, {"en": "Rangpo", "hi": "रंगपो"}, {"en": "Jorethang", "hi": "जोरेथांग"}],
    links: [
      { c: "services", u: "https://sso.sikkim.gov.in/", n: "Sikkim GO (SSO e-Services)", nh: "सिक्किम गो (ई-सेवाएं)" },
      { c: "land", u: "https://ilrms.sikkim.gov.in/", n: "ILRMS Sikkim", nh: "आईएलआरएमएस सिक्किम" },
      { c: "ration", u: "https://sikkimfcs.sikkim.gov.in/", n: "Food & Civil Supplies Department, Sikkim", nh: "खाद्य एवं नागरिक आपूर्ति विभाग, सिक्किम" },
      { c: "rti", u: "https://rtionline.sikkim.gov.in/", n: "RTI Online Sikkim", nh: "आरटीआई ऑनलाइन सिक्किम" },
      { c: "portal", u: "https://www.sikkim.gov.in/", n: "Government of Sikkim Portal", nh: "सिक्किम सरकार पोर्टल" },
    ],
    help: [{"num": "18003453236", "en": "PDS / ration toll-free helpline", "hi": "पीडीएस / राशन टोल-फ्री हेल्पलाइन"}] },
  { id: "tamil-nadu", type: "state", en: "Tamil Nadu", hi: "तमिलनाडु", crs: false,
    codes: ["TN"], aliases: ["Madras State", "Tamil Nad", "Tamilnadu", "तमिल नाडु"],
    cities: [{"en": "Chennai", "hi": "चेन्नई"}, {"en": "Coimbatore", "hi": "कोयंबटूर"}, {"en": "Madurai", "hi": "मदुरै"}, {"en": "Tiruchirappalli", "hi": "तिरुचिरापल्ली"}, {"en": "Salem", "hi": "सेलम"}, {"en": "Tirunelveli", "hi": "तिरुनेलवेली"}, {"en": "Vellore", "hi": "वेल्लोर"}, {"en": "", "hi": "इरोड"}, {"en": "Thoothukudi", "hi": "थूथुकुडी"}, {"en": "Thanjavur", "hi": "तंजावुर"}, {"en": "Madras", "hi": "मद्रास"}, {"en": "Trichy", "hi": "त्रिची"}],
    links: [
      { c: "services", u: "https://www.tnesevai.tn.gov.in/Citizen/", n: "TN e-Sevai", nh: "टीएन ई-सेवई" },
      { c: "land", u: "https://eservices.tn.gov.in/eservicesnew/home.html", n: "eServices Patta Chitta (Anytime/Anywhere)", nh: "ई-सर्विसेज़ पट्टा चिट्टा" },
      { c: "ration", u: "https://www.tnpds.gov.in/", n: "TNPDS", nh: "टीएनपीडीएस" },
      { c: "birth", u: "https://www.crstn.org/birth_death_tn/", n: "CRS Tamil Nadu (Birth and Death Registration)", nh: "सीआरएस तमिलनाडु (जन्म एवं मृत्यु पंजीकरण)" },
      { c: "grievance", u: "https://cmhelpline.tnega.org/portal/en/home", n: "CM Helpline - Mudhalvarin Mugavari", nh: "सीएम हेल्पलाइन - मुदलवरिन मुगवरी" },
      { c: "rti", u: "https://rtionline.tn.gov.in/", n: "Online RTI Tamil Nadu", nh: "ऑनलाइन आरटीआई तमिलनाडु" },
      { c: "portal", u: "https://www.tn.gov.in/", n: "Government of Tamil Nadu", nh: "तमिलनाडु सरकार" },
    ],
    help: [{"num": "1100", "en": "CM Helpline (Mudhalvarin Mugavari) for public grievances", "hi": "सीएम हेल्पलाइन (मुदलवरिन मुगवरी) जन शिकायत"}, {"num": "1800-425-1333", "en": "TN e-Sevai helpdesk (certificate services)", "hi": "टीएन ई-सेवई हेल्पडेस्क (प्रमाण पत्र सेवाएँ)"}] },
  { id: "telangana", type: "state", en: "Telangana", hi: "तेलंगाना", crs: false,
    codes: ["TG", "TS"], aliases: ["Telangana State", "Telengana", "तेलंगान"],
    cities: [{"en": "Hyderabad", "hi": "हैदराबाद"}, {"en": "Warangal", "hi": "वारंगल"}, {"en": "Nizamabad", "hi": "निज़ामाबाद"}, {"en": "Karimnagar", "hi": "करीमनगर"}, {"en": "Khammam", "hi": "खम्मम"}, {"en": "Ramagundam", "hi": "रामागुंडम"}, {"en": "Mahabubnagar", "hi": "महबूबनगर"}, {"en": "Nalgonda", "hi": "नलगोंडा"}, {"en": "Adilabad", "hi": "आदिलाबाद"}, {"en": "Siddipet", "hi": "सिद्दीपेट"}, {"en": "Secunderabad", "hi": "सिकंदराबाद"}],
    links: [
      { c: "services", u: "https://ts.meeseva.telangana.gov.in/meeseva/home.htm", n: "MeeSeva Telangana", nh: "मीसेवा तेलंगाना" },
      { c: "land", u: "https://bhubharati.telangana.gov.in/", n: "Bhu Bharati", nh: "भू भारती" },
      { c: "ration", u: "https://civilsupplies.telangana.gov.in/", n: "Consumer Affairs, Food & Civil Supplies Department, Telangana", nh: "उपभोक्ता मामले, खाद्य एवं नागरिक आपूर्ति विभाग, तेलंगाना" },
      { c: "birth", u: "https://ubd.telangana.gov.in/", n: "Unified Birth & Death Registration (UBD)", nh: "एकीकृत जन्म एवं मृत्यु पंजीकरण (यूबीडी)" },
      { c: "grievance", u: "https://cpgrams.ts.nic.in/", n: "Prajavani / CPGRAMS Telangana", nh: "प्रजावाणी / सीपीग्राम्स तेलंगाना" },
      { c: "portal", u: "https://www.telangana.gov.in/", n: "Government of Telangana", nh: "तेलंगाना सरकार" },
    ],
    help: [{"num": "1100", "en": "MeeSeva Call Centre", "hi": "मीसेवा कॉल सेंटर"}, {"num": "1800-425-1110", "en": "MeeSeva Call Centre (toll-free)", "hi": "मीसेवा कॉल सेंटर (टोल-फ्री)"}] },
  { id: "tripura", type: "state", en: "Tripura", hi: "त्रिपुरा", crs: true,
    codes: [], aliases: ["Tripura", "त्रिपुरा"],
    cities: [{"en": "Agartala", "hi": "अगरतला"}, {"en": "Dharmanagar", "hi": "धर्मनगर"}, {"en": "Kailashahar", "hi": "कैलाशहर"}, {"en": "Ambassa", "hi": "अम्बासा"}, {"en": "Khowai", "hi": "खोवाई"}, {"en": "Belonia", "hi": "बेलोनिया"}, {"en": "Bishramganj", "hi": "बिश्रामगंज"}, {"en": "Teliamura", "hi": "तेलियामुरा"}, {"en": "Sabroom", "hi": "सबरूम"}],
    links: [
      { c: "services", u: "https://edistrict.tripura.gov.in/", n: "Tripura e-District (Digital Seva)", nh: "त्रिपुरा ई-डिस्ट्रिक्ट (डिजिटल सेवा)" },
      { c: "land", u: "https://jami.tripura.gov.in/", n: "Jami – Tripura Land Records (e-Land)", nh: "जमी – त्रिपुरा भूमि अभिलेख (ई-लैंड)" },
      { c: "ration", u: "https://feasttr.gov.in/", n: "FEAST Tripura (Food & Civil Supplies)", nh: "फीस्ट त्रिपुरा (खाद्य एवं नागरिक आपूर्ति)" },
      { c: "grievance", u: "https://grievance.tripura.gov.in/", n: "CPGRAMS Tripura (State Public Grievance portal)", nh: "सीपीग्राम्स त्रिपुरा (राज्य लोक शिकायत पोर्टल)" },
      { c: "portal", u: "https://tripura.gov.in/", n: "Tripura State Portal", nh: "त्रिपुरा राज्य पोर्टल" },
    ],
    help: [{"num": "1800-345-3665", "en": "State consumer / PDS (ration) toll-free helpline", "hi": "राज्य उपभोक्ता / राशन (पीडीएस) टोल-फ्री हेल्पलाइन"}] },
  { id: "uttar-pradesh", type: "state", en: "Uttar Pradesh", hi: "उत्तर प्रदेश", crs: true,
    codes: ["UP"], aliases: ["UP state", "Uttar Pardesh", "Uttar Pradesh", "Uttarpradesh", "उ.प्र.", "उत्तर प्रदेश", "उत्तरप्रदेश", "यूपी"],
    cities: [{"en": "Lucknow", "hi": "लखनऊ"}, {"en": "Kanpur", "hi": "कानपुर"}, {"en": "Prayagraj", "hi": "प्रयागराज"}, {"en": "Varanasi", "hi": "वाराणसी"}, {"en": "Agra", "hi": "आगरा"}, {"en": "Ghaziabad", "hi": "गाज़ियाबाद"}, {"en": "Meerut", "hi": "मेरठ"}, {"en": "Gorakhpur", "hi": "गोरखपुर"}, {"en": "Bareilly", "hi": "बरेली"}, {"en": "Noida", "hi": "नोएडा"}, {"en": "Allahabad", "hi": "इलाहाबाद"}, {"en": "Banaras", "hi": "बनारस"}, {"en": "Benares", "hi": ""}],
    links: [
      { c: "services", u: "https://edistrict.up.gov.in/", n: "e-District Uttar Pradesh", nh: "ई-डिस्ट्रिक्ट उत्तर प्रदेश" },
      { c: "land", u: "https://upbhulekh.gov.in/", n: "UP Bhulekh", nh: "यूपी भूलेख" },
      { c: "ration", u: "https://fcs.up.gov.in/", n: "Food & Civil Supplies Department, Uttar Pradesh", nh: "खाद्य एवं रसद विभाग, उत्तर प्रदेश" },
      { c: "grievance", u: "https://jansunwai.up.nic.in/", n: "IGRS Jansunwai-Samadhan", nh: "जनसुनवाई-समाधान (आईजीआरएस)" },
      { c: "rti", u: "https://rtionline.up.gov.in/", n: "RTI Online Uttar Pradesh", nh: "आरटीआई ऑनलाइन उत्तर प्रदेश" },
      { c: "portal", u: "https://up.gov.in/", n: "Uttar Pradesh Government Portal", nh: "उत्तर प्रदेश सरकार पोर्टल" },
    ],
    help: [{"num": "1076", "en": "CM Helpline (IGRS/Jansunwai public grievances)", "hi": "मुख्यमंत्री हेल्पलाइन (जनसुनवाई/आईजीआरएस शिकायत)"}] },
  { id: "uttarakhand", type: "state", en: "Uttarakhand", hi: "उत्तराखंड", crs: true,
    codes: [], aliases: ["Uttarakhand", "Uttarakhand state", "Uttaranchal", "Uttrakhand", "उत्तरांचल", "उत्तराखंड", "उत्तराखण्ड"],
    cities: [{"en": "Dehradun", "hi": "देहरादून"}, {"en": "Haridwar", "hi": "हरिद्वार"}, {"en": "Roorkee", "hi": "रुड़की"}, {"en": "Haldwani", "hi": "हल्द्वानी"}, {"en": "Rudrapur", "hi": "रुद्रपुर"}, {"en": "Kashipur", "hi": "काशीपुर"}, {"en": "Rishikesh", "hi": "ऋषिकेश"}, {"en": "Nainital", "hi": "नैनीताल"}, {"en": "Almora", "hi": "अल्मोड़ा"}, {"en": "Pithoragarh", "hi": "पिथौरागढ़"}],
    links: [
      { c: "services", u: "https://eservices.uk.gov.in/", n: "Apuni Sarkar", nh: "अपणि सरकार" },
      { c: "land", u: "https://bhulekh.uk.gov.in/", n: "Bhulekh Uttarakhand", nh: "भूलेख उत्तराखंड" },
      { c: "ration", u: "https://fcs.uk.gov.in/", n: "Food, Civil Supplies & Consumer Affairs Department, Uttarakhand", nh: "खाद्य, नागरिक आपूर्ति एवं उपभोक्ता मामले विभाग, उत्तराखंड" },
      { c: "grievance", u: "https://cmhelpline.uk.gov.in/", n: "CM Helpline 1905", nh: "सीएम हेल्पलाइन 1905" },
      { c: "rti", u: "https://rtionline.uk.gov.in/", n: "RTI Online Uttarakhand", nh: "आरटीआई ऑनलाइन उत्तराखंड" },
      { c: "portal", u: "https://uk.gov.in/", n: "Uttarakhand Government Portal", nh: "उत्तराखंड सरकार पोर्टल" },
    ],
    help: [{"num": "1905", "en": "CM Helpline (public grievances)", "hi": "मुख्यमंत्री हेल्पलाइन (जन शिकायत)"}] },
  { id: "west-bengal", type: "state", en: "West Bengal", hi: "पश्चिम बंगाल", crs: false,
    codes: ["WB"], aliases: ["Bengal", "Paschim Banga", "Paschim Bangla", "Paschimbanga", "पश्चिम बंगाल", "पश्चिमबंग", "बंगाल"],
    cities: [{"en": "Kolkata", "hi": "कोलकाता"}, {"en": "Howrah", "hi": "हावड़ा"}, {"en": "Asansol", "hi": "आसनसोल"}, {"en": "Durgapur", "hi": "दुर्गापुर"}, {"en": "Siliguri", "hi": "सिलीगुड़ी"}, {"en": "Bardhaman", "hi": "बर्धमान"}, {"en": "Kharagpur", "hi": "खड़गपुर"}, {"en": "Malda", "hi": "मालदा"}, {"en": "Darjeeling", "hi": "दार्जिलिंग"}, {"en": "Haldia", "hi": "हल्दिया"}, {"en": "Calcutta", "hi": "कलकत्ता"}],
    links: [
      { c: "services", u: "https://edistrict.wb.gov.in/", n: "eDistrict 2.0 West Bengal", nh: "ई-डिस्ट्रिक्ट 2.0 पश्चिम बंगाल" },
      { c: "land", u: "https://banglarbhumi.gov.in/", n: "Banglarbhumi", nh: "बांग्लारभूमि" },
      { c: "ration", u: "https://food.wb.gov.in/", n: "Food & Supplies Department, West Bengal", nh: "खाद्य एवं आपूर्ति विभाग, पश्चिम बंगाल" },
      { c: "birth", u: "https://janma-mrityutathya.wb.gov.in/", n: "Janma-Mrityu Tathya", nh: "जन्म-मृत्यु तथ्य" },
      { c: "grievance", u: "https://cmo.wb.gov.in/", n: "CMO Grievance Portal, West Bengal", nh: "मुख्यमंत्री कार्यालय शिकायत पोर्टल, पश्चिम बंगाल" },
      { c: "portal", u: "https://wb.gov.in/", n: "Government of West Bengal Portal", nh: "पश्चिम बंगाल सरकार पोर्टल" },
    ],
    help: [{"num": "8282082820", "en": "Apnar Sarkar Apnar Pashe — help with government services (Mon–Sat, 9 AM–6 PM)", "hi": "आपनार सरकार आपनार पाशे — सरकारी सेवाओं में मदद (सोम–शनि, सुबह 9 से शाम 6)"}, {"num": "18003455505", "en": "Food & Supplies Department toll-free grievance helpline for ration/PDS issues (also 1967)", "hi": "खाद्य एवं आपूर्ति विभाग टोल फ्री शिकायत हेल्पलाइन – राशन/पीडीएस संबंधी (1967 भी)"}] },
];
